In [1]:
import geopandas as gpd
import pandas as pd
from pathlib import Path

# base path
base = Path("Areas-of-interest-POIs")

# build file paths
file_paths = [
    base / f"final_predictions_with_geometry{'' if i == 0 else f'_{i}'}.gpkg"
    for i in range(6)
]

gdfs = []

for path in file_paths:
    try:
        if path.exists():
            gdf = gpd.read_file(path)
            
            # skip empty files
            if len(gdf) > 0:
                gdfs.append(gdf)
                print(f"Loaded {path.name}: {len(gdf)} rows")
            else:
                print(f"Skipped empty file: {path.name}")
        else:
            print(f"File not found: {path.name}")

    except Exception as e:
        print(f"Error loading {path.name}: {e}")

# merge all
df = gpd.GeoDataFrame(pd.concat(gdfs, ignore_index=True), crs=gdfs[0].crs)

print(f"\nFinal merged dataset: {len(df)} rows")

Loaded final_predictions_with_geometry.gpkg: 548717 rows
Loaded final_predictions_with_geometry_1.gpkg: 47648 rows
Loaded final_predictions_with_geometry_2.gpkg: 4181 rows
Loaded final_predictions_with_geometry_3.gpkg: 500 rows
Loaded final_predictions_with_geometry_4.gpkg: 84 rows
Loaded final_predictions_with_geometry_5.gpkg: 44 rows

Final merged dataset: 601174 rows

In [2]:
df.columns

Index(['index', 'gml_id', 'volume_m3', 'label_en', 'osm_building_type',
       'osm_landuse_class', 'osm_landuse_name', 'gfk_class',
       'ALKIS_Landuse_info', 'osm_names', 'alkis_address', 'email', 'amenity',
       'building', 'shop', 'tourism', 'information', 'tags_search',
       'additional_information', 'website', 'sentence', 'interpreted_type',
       'mid_labels', 'bosserhof_class', 'mid_label', 'geometry', 'gml_id_pred',
       'short_reason'],
      dtype='object')

In [3]:
df.head()

,index,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,...,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class,mid_label,geometry,gml_id_pred,short_reason
0,4.0,4,351.716079,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,This row describes one building. Building iden...,residential building,[],None,None,MULTIPOLYGON Z (((608902.529 5796965.286 84.84...,NaN,NaN
1,5.0,5,91.824388,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,This row describes one building. Building iden...,residential building,[],None,None,MULTIPOLYGON Z (((609700.608 5796992.753 77.70...,NaN,NaN
2,6.0,6,9.680736,Buildings for business or commerce,None,residential,None,Gebäude,public_office,None,...,None,None,This row describes one building. Building iden...,public office building,['work' 'errands'],customer-oriented services,['work' 'errands'],MULTIPOLYGON Z (((609913.308 5797159.22 78.757...,NaN,NaN
3,7.0,7,32.861208,Buildings for supply,None,residential,None,Gebäude,residence,None,...,None,None,This row describes one building. Building iden...,residential building,[],None,None,MULTIPOLYGON Z (((609914.965 5797536.391 79.54...,NaN,NaN
4,8.0,12,51.354285,residential buildings,None,allotments,KGV Auf dem Klei,Gebäude,None,None,...,None,None,This row describes one building. Building iden...,Allotment garden cottage (Kleingartenhaus),['leisure'],None,['leisure'],MULTIPOLYGON Z (((609168.166 5797801.912 86.23...,NaN,NaN

In [4]:
df = df.drop(columns=['sentence', 'interpreted_type', 'mid_labels', 'gml_id_pred', 'short_reason'],axis=1)

df.head()

,index,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,...,building,shop,tourism,information,tags_search,additional_information,website,bosserhof_class,mid_label,geometry
0,4.0,4,351.716079,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,None,None,None,MULTIPOLYGON Z (((608902.529 5796965.286 84.84...
1,5.0,5,91.824388,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,None,None,None,MULTIPOLYGON Z (((609700.608 5796992.753 77.70...
2,6.0,6,9.680736,Buildings for business or commerce,None,residential,None,Gebäude,public_office,None,...,None,None,None,None,None,None,None,customer-oriented services,['work' 'errands'],MULTIPOLYGON Z (((609913.308 5797159.22 78.757...
3,7.0,7,32.861208,Buildings for supply,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,None,None,None,MULTIPOLYGON Z (((609914.965 5797536.391 79.54...
4,8.0,12,51.354285,residential buildings,None,allotments,KGV Auf dem Klei,Gebäude,None,None,...,None,None,None,None,None,None,None,None,['leisure'],MULTIPOLYGON Z (((609168.166 5797801.912 86.23...

In [5]:
df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 601174 entries, 0 to 601173
Data columns (total 23 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   index                   601130 non-null  float64
 1   gml_id                  601174 non-null  object
 2   volume_m3               601174 non-null  float64
 3   label_en                547150 non-null  object
 4   osm_building_type       59378 non-null   object
 5   osm_landuse_class       533537 non-null  object
 6   osm_landuse_name        48725 non-null   object
 7   gfk_class               547150 non-null  object
 8   ALKIS_Landuse_info      519592 non-null  object
 9   osm_names               18219 non-null   object
 10  alkis_address           556575 non-null  object
 11  email                   878 non-null     object
 12  amenity                 7413 non-null    object
 13  building                5023 non-null    object
 14  shop                    4170 non-null    object
 15  tourism                 1131 non-null    object
 16  information             0 non-null       object
 17  tags_search             8850 non-null    object
 18  additional_information  2344 non-null    object
 19  website                 3618 non-null    object
 20  bosserhof_class         154287 non-null  object
 21  mid_label               157947 non-null  object
 22  geometry                601174 non-null  geometry
dtypes: float64(2), geometry(1), object(20)
memory usage: 105.5+ MB

In [6]:
df_final = df[['gml_id','volume_m3','osm_names','bosserhof_class','mid_label','geometry']]
df_final.head()

,gml_id,volume_m3,osm_names,bosserhof_class,mid_label,geometry
0,4,351.716079,None,None,None,MULTIPOLYGON Z (((608902.529 5796965.286 84.84...
1,5,91.824388,None,None,None,MULTIPOLYGON Z (((609700.608 5796992.753 77.70...
2,6,9.680736,None,customer-oriented services,['work' 'errands'],MULTIPOLYGON Z (((609913.308 5797159.22 78.757...
3,7,32.861208,None,None,None,MULTIPOLYGON Z (((609914.965 5797536.391 79.54...
4,12,51.354285,None,None,['leisure'],MULTIPOLYGON Z (((609168.166 5797801.912 86.23...

In [7]:
df['mid_label'].value_counts()

mid_label
['work']                                                          100668
['work' 'business']                                                15813
['leisure']                                                         7557
['work' 'errands']                                                  7339
['work' 'retail_non_daily']                                         4426
                                                                   ...
['retail_non_daily' 'leisure' 'meetup']                                1
['work' 'sports' 'lessons' 'leisure' 'meetup']                         1
['work' 'retail_daily' 'retail_non_daily' 'leisure' 'lessons']         1
['retail_daily' 'lessons' 'errands']                                   1
['work' 'retail_non_daily' 'lessons']                                  1
Name: count, Length: 408, dtype: int64

In [8]:
df_final = df_final.dropna(subset=['mid_label'])
df_final.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 157947 entries, 2 to 601127
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   gml_id           157947 non-null  object
 1   volume_m3        157947 non-null  float64
 2   osm_names        16818 non-null   object
 3   bosserhof_class  154260 non-null  object
 4   mid_label        157947 non-null  object
 5   geometry         157947 non-null  geometry
dtypes: float64(1), geometry(1), object(4)
memory usage: 8.4+ MB

In [9]:
df_final.to_file("Areas-of-interest-POIs/final_dataset(with_classification_labels).gpkg", driver="GPKG")

In [10]:
df_final['bosserhof_class'].value_counts()

bosserhof_class
normal office                                                        76082
Services                                                             12379
retail (small-scale)                                                 12085
Industrial operations / Production                                    8074
customer-oriented services                                            7337
                                                                     ...
suppliers for car dealerships                                            1
Facilities for culture, leisure and sports/entertainment, culture        1
Services: business-oriented services                                     1
Facilities for culture, leisure and sports – fitness / wellness          1
services – customer-oriented services                                    1
Name: count, Length: 148, dtype: int64