In [1]:
import geopandas as gpd
import pandas as pd
from pathlib import Path

# base path
base = Path("Areas-of-interest-POIs")

# build file paths
file_paths = [
    base / f"final_predictions_with_geometry{'' if i == 0 else f'_{i}'}.gpkg"
    for i in range(6)
]

gdfs = []

for path in file_paths:
    try:
        if path.exists():
            gdf = gpd.read_file(path)
            
            # skip empty files
            if len(gdf) > 0:
                gdfs.append(gdf)
                print(f"Loaded {path.name}: {len(gdf)} rows")
            else:
                print(f"Skipped empty file: {path.name}")
        else:
            print(f"File not found: {path.name}")

    except Exception as e:
        print(f"Error loading {path.name}: {e}")

# merge all
df = gpd.GeoDataFrame(pd.concat(gdfs, ignore_index=True), crs=gdfs[0].crs)

print(f"\nFinal merged dataset: {len(df)} rows")

Loaded final_predictions_with_geometry.gpkg: 548717 rows
Loaded final_predictions_with_geometry_1.gpkg: 47648 rows
Loaded final_predictions_with_geometry_2.gpkg: 4181 rows
Loaded final_predictions_with_geometry_3.gpkg: 500 rows
Loaded final_predictions_with_geometry_4.gpkg: 84 rows
Loaded final_predictions_with_geometry_5.gpkg: 44 rows

Final merged dataset: 601174 rows

In [2]:
df.columns

Index(['index', 'gml_id', 'volume_m3', 'label_en', 'osm_building_type',
       'osm_landuse_class', 'osm_landuse_name', 'gfk_class',
       'ALKIS_Landuse_info', 'osm_names', 'alkis_address', 'email', 'amenity',
       'building', 'shop', 'tourism', 'information', 'tags_search',
       'additional_information', 'website', 'sentence', 'interpreted_type',
       'mid_labels', 'bosserhof_class', 'mid_label', 'geometry', 'gml_id_pred',
       'short_reason'],
      dtype='object')

In [3]:
df.head()

,index,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,...,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class,mid_label,geometry,gml_id_pred,short_reason
0,4.0,4,351.716079,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,This row describes one building. Building iden...,residential building,[],None,None,MULTIPOLYGON Z (((608902.529 5796965.286 84.84...,NaN,NaN
1,5.0,5,91.824388,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,This row describes one building. Building iden...,residential building,[],None,None,MULTIPOLYGON Z (((609700.608 5796992.753 77.70...,NaN,NaN
2,6.0,6,9.680736,Buildings for business or commerce,None,residential,None,Gebäude,public_office,None,...,None,None,This row describes one building. Building iden...,public office building,['work' 'errands'],customer-oriented services,['work' 'errands'],MULTIPOLYGON Z (((609913.308 5797159.22 78.757...,NaN,NaN
3,7.0,7,32.861208,Buildings for supply,None,residential,None,Gebäude,residence,None,...,None,None,This row describes one building. Building iden...,residential building,[],None,None,MULTIPOLYGON Z (((609914.965 5797536.391 79.54...,NaN,NaN
4,8.0,12,51.354285,residential buildings,None,allotments,KGV Auf dem Klei,Gebäude,None,None,...,None,None,This row describes one building. Building iden...,Allotment garden cottage (Kleingartenhaus),['leisure'],None,['leisure'],MULTIPOLYGON Z (((609168.166 5797801.912 86.23...,NaN,NaN

In [4]:
df = df.drop(columns=['sentence', 'interpreted_type', 'mid_labels', 'gml_id_pred', 'short_reason'],axis=1)

df.head()

,index,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,...,building,shop,tourism,information,tags_search,additional_information,website,bosserhof_class,mid_label,geometry
0,4.0,4,351.716079,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,None,None,None,MULTIPOLYGON Z (((608902.529 5796965.286 84.84...
1,5.0,5,91.824388,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,None,None,None,MULTIPOLYGON Z (((609700.608 5796992.753 77.70...
2,6.0,6,9.680736,Buildings for business or commerce,None,residential,None,Gebäude,public_office,None,...,None,None,None,None,None,None,None,customer-oriented services,['work' 'errands'],MULTIPOLYGON Z (((609913.308 5797159.22 78.757...
3,7.0,7,32.861208,Buildings for supply,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,None,None,None,MULTIPOLYGON Z (((609914.965 5797536.391 79.54...
4,8.0,12,51.354285,residential buildings,None,allotments,KGV Auf dem Klei,Gebäude,None,None,...,None,None,None,None,None,None,None,None,['leisure'],MULTIPOLYGON Z (((609168.166 5797801.912 86.23...

In [5]:
df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 601174 entries, 0 to 601173
Data columns (total 23 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   index                   601130 non-null  float64
 1   gml_id                  601174 non-null  object
 2   volume_m3               601174 non-null  float64
 3   label_en                547150 non-null  object
 4   osm_building_type       59378 non-null   object
 5   osm_landuse_class       533537 non-null  object
 6   osm_landuse_name        48725 non-null   object
 7   gfk_class               547150 non-null  object
 8   ALKIS_Landuse_info      519592 non-null  object
 9   osm_names               18219 non-null   object
 10  alkis_address           556575 non-null  object
 11  email                   878 non-null     object
 12  amenity                 7413 non-null    object
 13  building                5023 non-null    object
 14  shop                    4170 non-null    object
 15  tourism                 1131 non-null    object
 16  information             0 non-null       object
 17  tags_search             8850 non-null    object
 18  additional_information  2344 non-null    object
 19  website                 3618 non-null    object
 20  bosserhof_class         154287 non-null  object
 21  mid_label               157947 non-null  object
 22  geometry                601174 non-null  geometry
dtypes: float64(2), geometry(1), object(20)
memory usage: 105.5+ MB

In [6]:
df_final = df[['gml_id','volume_m3','osm_names','bosserhof_class','mid_label','geometry']]
df_final.head()

,gml_id,volume_m3,osm_names,bosserhof_class,mid_label,geometry
0,4,351.716079,None,None,None,MULTIPOLYGON Z (((608902.529 5796965.286 84.84...
1,5,91.824388,None,None,None,MULTIPOLYGON Z (((609700.608 5796992.753 77.70...
2,6,9.680736,None,customer-oriented services,['work' 'errands'],MULTIPOLYGON Z (((609913.308 5797159.22 78.757...
3,7,32.861208,None,None,None,MULTIPOLYGON Z (((609914.965 5797536.391 79.54...
4,12,51.354285,None,None,['leisure'],MULTIPOLYGON Z (((609168.166 5797801.912 86.23...

In [7]:
df['mid_label'].value_counts()

mid_label
['work']                                                          100668
['work' 'business']                                                15813
['leisure']                                                         7557
['work' 'errands']                                                  7339
['work' 'retail_non_daily']                                         4426
                                                                   ...
['retail_non_daily' 'leisure' 'meetup']                                1
['work' 'sports' 'lessons' 'leisure' 'meetup']                         1
['work' 'retail_daily' 'retail_non_daily' 'leisure' 'lessons']         1
['retail_daily' 'lessons' 'errands']                                   1
['work' 'retail_non_daily' 'lessons']                                  1
Name: count, Length: 408, dtype: int64

In [8]:
df_final = df_final.dropna(subset=['mid_label'])
df_final.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 157947 entries, 2 to 601127
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   gml_id           157947 non-null  object
 1   volume_m3        157947 non-null  float64
 2   osm_names        16818 non-null   object
 3   bosserhof_class  154260 non-null  object
 4   mid_label        157947 non-null  object
 5   geometry         157947 non-null  geometry
dtypes: float64(1), geometry(1), object(4)
memory usage: 8.4+ MB

In [9]:
import re

def clean_bosserhof_label(val):
    if pd.isna(val):
        return val  # keep NaN as is
    
    # convert to string (safety)
    val = str(val)
    
    # 1. lowercase
    val = val.lower()
    
    # 2. remove special characters (keep letters, numbers, spaces)
    val = re.sub(r'[^a-z0-9\s]', ' ', val)
    
    # 3. remove extra spaces
    val = re.sub(r'\s+', ' ', val).strip()
    
    return val

# Apply to column
df_final['bosserhof_class'] = df_final['bosserhof_class'].apply(clean_bosserhof_label)

In [10]:
df_final['bosserhof_class'].value_counts()

bosserhof_class
normal office                                        76082
services                                             15487
retail small scale                                   12125
industrial operations production                      8269
customer oriented services                            7356
                                                     ...
service oriented customer service                        1
yards depots storage areas and construction yards        1
services restaurants gastronomy                          1
suppliers for car dealerships                            1
public facilities churches not listed                    1
Name: count, Length: 61, dtype: int64

In [11]:
raw_text = """
Transport
Yards, depots, storage areas, construction yards
Industrial operations / Production
highly productive industries / machine / material or space intensive
others
Crafts and trades
craft businesses
craft courtyards
Services
normal office
open-plan office
business-oriented services
customer-oriented services
hotels
hotels with conference areas
restaurants / gastronomy
suppliers for car dealerships
vehicle / electrical repair
customer service
car dealerships
Retail
wholesale
retail (small-scale)
discount stores
DIY stores
furniture stores
hypermarkets / superstores
shopping centers
self-service department stores
department stores
factory outlet centers
Public facilities
schools
universities
research institutes
kindergartens
hospitals
nursing homes
Facilities for culture, leisure and sports
entertainment, culture
large cinemas
musical theatres
large discos, fun / leisure pools
arenas, large events
theme parks
fitness / wellness
"""

def clean_label(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)   # remove special chars
    text = re.sub(r'\s+', ' ', text).strip()   # remove extra spaces
    return text

# split into lines, remove empty ones, clean each line
clean_labels = [
    clean_label(line)
    for line in raw_text.splitlines()
    if line.strip()
]

# # print one below another
# for label in clean_labels:
#     print(label)

In [12]:
# count non-empty lines (labels)
num_labels = len([line for line in raw_text.splitlines() if line.strip()])

print(num_labels)

46

In [13]:
import numpy as np

mapping_dict = {
    "others" : "others industrial",
    "industrial operations production others": "industrial operations production",
    "highly productive industries" : "highly productive industries machine material or space intensive",
    "services normal office": "normal office",
    "industrial operations others": "industrial operations production",
    "industrial operations production highly productive industries machine material or space intensive": "highly productive industries machine material or space intensive",
    "yards depots storage areas" : "yards depots storage areas construction yards",
    "retail retail small scale : retail small scale": "retail small scale",
    "services customer oriented services": "customer oriented services",
    "services business oriented services": "business oriented services",
    "facilities for culture leisure and sports fitness wellness": "fitness wellness",
    "facilities for culture leisure and sports entertainment culture": "entertainment culture",
    "industrial operations highly productive industries machine material or space intensive" : "highly productive industries machine material or space intensive",
    "fun leisure pools": "large discos fun leisure pools",
    "service oriented customer service": "customer oriented services",
    "yards depots storage areas and construction yards": "yards depots storage areas construction yards",
    "services restaurants gastronomy" : "restaurants gastronomy"
}


parsed_mapping = {}

for k, v in mapping_dict.items():
    left_side = k.split(" : ")[0].strip()
    parsed_mapping[left_side] = v

col = "bosserhof_class"

# keep original just in case
df_final[col + "_original"] = df_final[col]

# apply mapping only where match exists
df_final[col] = df_final[col].replace(parsed_mapping)

# convert None to real NaN
df_final[col] = df_final[col].where(df_final[col].notna(), np.nan)

column_values = set(df_final[col + "_original"].dropna().astype(str).str.strip().unique())
mapping_keys = set(parsed_mapping.keys())

unused_mapping_keys = sorted(mapping_keys - column_values)

if unused_mapping_keys:
    print("These mapping keys were NOT found in the dataframe column:")
    for x in unused_mapping_keys:
        print("-", x)
else:
    print("All mapping keys were found in the dataframe.")

mapped_values = set(parsed_mapping.keys())
remaining_unmapped = sorted(
    set(df_final[col + "_original"].dropna().astype(str).str.strip().unique()) - mapped_values
)

# print("\nValues still present in original column that were NOT in your mapping:")
# for x in remaining_unmapped:
#     print("-", x)

All mapping keys were found in the dataframe.

In [14]:
len(df_final['bosserhof_class'].unique())

46

In [15]:
df_final['bosserhof_class'].unique()

array(['customer oriented services', nan, 'normal office', 'services',
       'craft businesses', 'retail small scale', 'kindergartens',
       'industrial operations production',
       'yards depots storage areas construction yards',
       'facilities for culture leisure and sports', 'fitness wellness',
       'entertainment culture', 'business oriented services',
       'others industrial', 'restaurants gastronomy',
       'vehicle electrical repair',
       'highly productive industries machine material or space intensive',
       'retail', 'public facilities', 'research institutes', 'transport',
       'discount stores', 'nursing homes', 'schools', 'universities',
       'large discos fun leisure pools', 'car dealerships',
       'customer service', 'furniture stores', 'hotels', 'wholesale',
       'shopping centers', 'diy stores', 'hospitals',
       'arenas large events', 'hypermarkets superstores', 'large cinemas',
       'department stores', 'craft courtyards', 'open plan office',
       'theme parks', 'hotels with conference areas',
       'factory outlet centers', 'suppliers for car dealerships',
       'self service department stores',
       'public facilities churches not listed'], dtype=object)

In [16]:
df_final.head()
df_final = df_final.drop(columns=['bosserhof_class_original'],axis=1)

In [17]:
df_final.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 157947 entries, 2 to 601127
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   gml_id           157947 non-null  object
 1   volume_m3        157947 non-null  float64
 2   osm_names        16818 non-null   object
 3   bosserhof_class  154260 non-null  object
 4   mid_label        157947 non-null  object
 5   geometry         157947 non-null  geometry
dtypes: float64(1), geometry(1), object(4)
memory usage: 8.4+ MB

In [18]:
text = """
transport : 200 / 0.5
yards depots storage areas construction yards : 100-150 / 0.7-1,0
industrial operations production 
highly productive industries machine material or space intensive : 100-150 / 0.7-1.0
others industrial : 50-60 / 1.7-2.0
crafts and trades
craft businesses : 40-80 / 1.3-2.5
craft courtyards : 50-60 / 1.7-2.0
services
normal Office : 30-40 / 2.5-3.3
open plan Office :20-30 / 3.3-5.0
business oriented services : 10-50 / 2.0-5.0
customer oriented services : 25-50 / 2.0-4.0
Hotels : 50-100 / 1.0-2.0
hotels with conference Areas : 110-150 / 0.7-0.9 
restaurants gastronomy : 40-80 / 1.3-2.5
suppliers for car dealerships : 60 / 1.7
vehicle electrical repair :30-60 / 1.7-2.3
customer Service : 30 / 3.3
car dealerships : 150 / 0.7
retail
wholesale : 35-50 / 2.0-2.9
retail small scale : 20-50 / 2.5-5.0
discount stores : 90-140 / 0.7-1.1
diy stores : 125-150 / 0.7-0.8
furniture stores: 140-260 / 0.4-0.7
hypermarkets superstores : 70-100 / 1.0-1.4
shopping centers : 25-45 / 2.2-4.0
self service department stores : 85-100 / 1.0-1.2
department stores : 55-75 / 1.3-1.8
factory outlet centers : 40-55 / 1.8-2.5
public facilities
schools : 65-200 / 0.5-1.5
universities : 100-200 / 0.5-1.0
research institutes : 65-100 / 1.0-1.5
kindergartens : 35-60 / 1.7-2.9
hospitals : 65-100 / 1.0-1.5
nursing homes : xx / 0.45-0.80
facilities for culture leisure and sports
entertainment culture : 60 / 1.67
large cinemas : 120 / 0.83
musical theatres : 70 / 1.43
large discos fun leisure pools : 60 / 0.8
arenas large events : 70 / 1.43
theme parks : 60 / 1.67
fitness wellness : 125 / 0.8
"""

def parse_weight(value_str):
    value_str = value_str.strip().replace(",", ".")
    
    if "-" in value_str:
        a, b = value_str.split("-", 1)
        return (float(a.strip()) + float(b.strip())) / 2
    else:
        return float(value_str)

lines = [line.strip() for line in text.splitlines() if line.strip()]

label_weights = {}
group_children = {}
current_group = None

for line in lines:
    # case 1: line has actual value
    if ":" in line and "/" in line:
        label, right_part = line.split(":", 1)
        label = label.strip()
        after_slash = right_part.split("/")[-1].strip()

        try:
            weight = parse_weight(after_slash)
            label_weights[label] = weight

            # if currently inside a main class, attach this subclass to it
            if current_group is not None:
                group_children.setdefault(current_group, []).append(weight)

        except ValueError:
            print(f"Could not parse: {line}")

    # case 2: line has no value => treat as new main class heading
    else:
        current_group = line
        group_children.setdefault(current_group, [])

# now compute average for group headings
for group, values in group_children.items():
    if values:
        label_weights[group] = sum(values) / len(values)

# round all values
label_weights = {k: round(v, 2) for k, v in label_weights.items()}

print(label_weights)

{'transport': 0.5, 'yards depots storage areas construction yards': 0.85, 'highly productive industries machine material or space intensive': 0.85, 'others industrial': 1.85, 'craft businesses': 1.9, 'craft courtyards': 1.85, 'normal Office': 2.9, 'open plan Office': 4.15, 'business oriented services': 3.5, 'customer oriented services': 3.0, 'Hotels': 1.5, 'hotels with conference Areas': 0.8, 'restaurants gastronomy': 1.9, 'suppliers for car dealerships': 1.7, 'vehicle electrical repair': 2.0, 'customer Service': 3.3, 'car dealerships': 0.7, 'wholesale': 2.45, 'retail small scale': 3.75, 'discount stores': 0.9, 'diy stores': 0.75, 'furniture stores': 0.55, 'hypermarkets superstores': 1.2, 'shopping centers': 3.1, 'self service department stores': 1.1, 'department stores': 1.55, 'factory outlet centers': 2.15, 'schools': 1.0, 'universities': 0.75, 'research institutes': 1.25, 'kindergartens': 2.3, 'hospitals': 1.25, 'nursing homes': 0.62, 'entertainment culture': 1.67, 'large cinemas': 0.83, 'musical theatres': 1.43, 'large discos fun leisure pools': 0.8, 'arenas large events': 1.43, 'theme parks': 1.67, 'fitness wellness': 0.8, 'industrial operations production': 1.35, 'crafts and trades': 1.88, 'services': 2.31, 'retail': 1.75, 'public facilities': 1.2, 'facilities for culture leisure and sports': 1.23}

In [19]:
# Normalize weight dictionary keys to lowercase
weight_dict = {str(k).strip().lower(): v for k, v in label_weights.items()}

# Calculate potentials directly
df_final["potentials"] = (
    df_final["volume_m3"] *
    df_final["bosserhof_class"]
      .astype(str)
      .str.strip()
      .str.lower()
      .replace(["none", "nan"], np.nan)
      .map(weight_dict)
).round(2)

df_final.head()

,gml_id,volume_m3,osm_names,bosserhof_class,mid_label,geometry,potentials
2,6,9.680736,None,customer oriented services,['work' 'errands'],MULTIPOLYGON Z (((609913.308 5797159.22 78.757...,29.04
4,12,51.354285,None,NaN,['leisure'],MULTIPOLYGON Z (((609168.166 5797801.912 86.23...,NaN
8,0,931.423451,None,normal office,['work'],MULTIPOLYGON Z (((609554.181 5797264.172 78.94...,2701.13
9,1,1275.527533,None,normal office,['work'],MULTIPOLYGON Z (((608098.849 5796746.146 83.91...,3699.03
10,2,229.902499,None,normal office,['work'],"MULTIPOLYGON Z (((608926.355 5797165.768 84.6,...",666.72

In [20]:
df_final.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 157947 entries, 2 to 601127
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   gml_id           157947 non-null  object
 1   volume_m3        157947 non-null  float64
 2   osm_names        16818 non-null   object
 3   bosserhof_class  154260 non-null  object
 4   mid_label        157947 non-null  object
 5   geometry         157947 non-null  geometry
 6   potentials       154259 non-null  float64
dtypes: float64(2), geometry(1), object(4)
memory usage: 9.6+ MB

In [21]:
df_final = df_final.dropna(subset=['bosserhof_class'])
df_final.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 154260 entries, 2 to 601127
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   gml_id           154260 non-null  object
 1   volume_m3        154260 non-null  float64
 2   osm_names        16689 non-null   object
 3   bosserhof_class  154260 non-null  object
 4   mid_label        154260 non-null  object
 5   geometry         154260 non-null  geometry
 6   potentials       154259 non-null  float64
dtypes: float64(2), geometry(1), object(4)
memory usage: 9.4+ MB

In [22]:
df_final = df_final[df_final["volume_m3"] >= 30]

In [23]:
df_final.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 145495 entries, 8 to 601127
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   gml_id           145495 non-null  object
 1   volume_m3        145495 non-null  float64
 2   osm_names        16499 non-null   object
 3   bosserhof_class  145495 non-null  object
 4   mid_label        145495 non-null  object
 5   geometry         145495 non-null  geometry
 6   potentials       145494 non-null  float64
dtypes: float64(2), geometry(1), object(4)
memory usage: 8.9+ MB

In [24]:
df_final[df_final['potentials'].isna()]

,gml_id,volume_m3,osm_names,bosserhof_class,mid_label,geometry,potentials
566251,219583,3816.905572,['Dorfkirche'],public facilities churches not listed,['meetup' 'work'],MULTIPOLYGON Z (((617780.038 5790098.898 165.9...,NaN

In [25]:
df_final = df_final.dropna(subset=['potentials'])
df_final.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 145494 entries, 8 to 601127
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   gml_id           145494 non-null  object
 1   volume_m3        145494 non-null  float64
 2   osm_names        16498 non-null   object
 3   bosserhof_class  145494 non-null  object
 4   mid_label        145494 non-null  object
 5   geometry         145494 non-null  geometry
 6   potentials       145494 non-null  float64
dtypes: float64(2), geometry(1), object(4)
memory usage: 8.9+ MB

In [26]:
df_final.to_file("Areas-of-interest-POIs/final_potentials_calculation.gpkg", layer="final_potentials_calculation", driver="GPKG")