In [1]:
import pandas as pd

df = pd.read_parquet("predictions_checkpoint(error-rows)-4.parquet")
df.head()

,index,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,...,shop,tourism,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class
0,341.0,4841,43.316556,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,general_building_context: building_label=Build...,Commercial building (business or commerce),[work],normal office
1,342.0,4842,57.939536,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,general_building_context: building_label=Build...,Commercial building (business or commerce),[work],normal office
2,343.0,4878,124.981109,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,general_building_context: building_label=Build...,Commercial building (business or commerce),[work],normal office
3,389.0,5796,61.222193,residential buildings,None,allotments,KGV Thune,Gebäude,None,None,...,None,None,None,None,None,None,general_building_context: building_label=resid...,Residential building (allotment),[],None
4,70.0,1202,46.739183,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,general_building_context: building_label=Build...,error,[],None

In [2]:
df['interpreted_type'].value_counts()

interpreted_type
error                                                     721
Commercial building                                       425
residential building                                      239
Building for business or commerce                         236
Office building                                           174
                                                         ...
Public facility                                             1
service building                                            1
Building for business or commerce at Schlewecker Trift      1
transportation building                                     1
carport                                                     1
Name: count, Length: 245, dtype: int64

In [3]:
df[df['interpreted_type'] == 'error'].to_parquet("error_predictions-5.parquet")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2949 entries, 0 to 2948
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   index                   1204 non-null   float64
 1   gml_id                  2949 non-null   object
 2   volume_m3               2949 non-null   float64
 3   label_en                2825 non-null   object
 4   osm_building_type       155 non-null    object
 5   osm_landuse_class       2760 non-null   object
 6   osm_landuse_name        361 non-null    object
 7   gfk_class               2825 non-null   object
 8   ALKIS_Landuse_info      2573 non-null   object
 9   osm_names               51 non-null     object
 10  alkis_address           2832 non-null   object
 11  email                   0 non-null      object
 12  amenity                 14 non-null     object
 13  building                14 non-null     object
 14  shop                    1 non-null      object
 15  tourism                 0 non-null      object
 16  information             0 non-null      object
 17  tags_search             13 non-null     object
 18  additional_information  13 non-null     object
 19  website                 6 non-null      object
 20  sentence                2949 non-null   object
 21  interpreted_type        2949 non-null   object
 22  mid_labels              2949 non-null   object
 23  bosserhof_class         1719 non-null   object
dtypes: float64(2), object(22)
memory usage: 553.1+ KB

In [5]:
# Remove rows where interpreted_type == 'error'
df = df[df['interpreted_type'] != 'error']

In [6]:
# df.to_parquet("clean_predictions-1.parquet")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2228 entries, 0 to 2947
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   index                   920 non-null    float64
 1   gml_id                  2228 non-null   object
 2   volume_m3               2228 non-null   float64
 3   label_en                2133 non-null   object
 4   osm_building_type       123 non-null    object
 5   osm_landuse_class       2082 non-null   object
 6   osm_landuse_name        284 non-null    object
 7   gfk_class               2133 non-null   object
 8   ALKIS_Landuse_info      1940 non-null   object
 9   osm_names               43 non-null     object
 10  alkis_address           2138 non-null   object
 11  email                   0 non-null      object
 12  amenity                 12 non-null     object
 13  building                12 non-null     object
 14  shop                    1 non-null      object
 15  tourism                 0 non-null      object
 16  information             0 non-null      object
 17  tags_search             11 non-null     object
 18  additional_information  11 non-null     object
 19  website                 4 non-null      object
 20  sentence                2228 non-null   object
 21  interpreted_type        2228 non-null   object
 22  mid_labels              2228 non-null   object
 23  bosserhof_class         1719 non-null   object
dtypes: float64(2), object(22)
memory usage: 435.2+ KB

In [8]:
df.head()

,index,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,...,shop,tourism,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class
0,341.0,4841,43.316556,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,general_building_context: building_label=Build...,Commercial building (business or commerce),[work],normal office
1,342.0,4842,57.939536,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,general_building_context: building_label=Build...,Commercial building (business or commerce),[work],normal office
2,343.0,4878,124.981109,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,None,None,None,None,None,None,general_building_context: building_label=Build...,Commercial building (business or commerce),[work],normal office
3,389.0,5796,61.222193,residential buildings,None,allotments,KGV Thune,Gebäude,None,None,...,None,None,None,None,None,None,general_building_context: building_label=resid...,Residential building (allotment),[],None
8,390.0,5798,88.065849,residential buildings,None,allotments,KGV Thune,Gebäude,None,None,...,None,None,None,None,None,None,general_building_context: building_label=resid...,Residential building (allotment hut),[],None

In [9]:
import numpy as np

df['mid_label'] = df['mid_labels'].apply(
    lambda x: np.nan if (
        (isinstance(x, list) and len(x) == 0) or
        (isinstance(x, np.ndarray) and x.size == 0)
    ) else x
)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2228 entries, 0 to 2947
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   index                   920 non-null    float64
 1   gml_id                  2228 non-null   object
 2   volume_m3               2228 non-null   float64
 3   label_en                2133 non-null   object
 4   osm_building_type       123 non-null    object
 5   osm_landuse_class       2082 non-null   object
 6   osm_landuse_name        284 non-null    object
 7   gfk_class               2133 non-null   object
 8   ALKIS_Landuse_info      1940 non-null   object
 9   osm_names               43 non-null     object
 10  alkis_address           2138 non-null   object
 11  email                   0 non-null      object
 12  amenity                 12 non-null     object
 13  building                12 non-null     object
 14  shop                    1 non-null      object
 15  tourism                 0 non-null      object
 16  information             0 non-null      object
 17  tags_search             11 non-null     object
 18  additional_information  11 non-null     object
 19  website                 4 non-null      object
 20  sentence                2228 non-null   object
 21  interpreted_type        2228 non-null   object
 22  mid_labels              2228 non-null   object
 23  bosserhof_class         1719 non-null   object
 24  mid_label               1340 non-null   object
dtypes: float64(2), object(23)
memory usage: 452.6+ KB

In [11]:
df = df.reset_index()

In [12]:
import geopandas as gpd

gdf_geom = gpd.read_file("condensed_buildings_with_pois.gpkg")

gdf_geom["gml_id"] = gdf_geom["gml_id"].astype(str)
df["gml_id"] = df["gml_id"].astype(str)

geom_df = gdf_geom[["gml_id", "geometry"]].copy()

merged_df = df.merge(geom_df, on="gml_id", how="left")

final_gdf = gpd.GeoDataFrame(merged_df, geometry="geometry", crs=gdf_geom.crs)

final_gdf.to_file("final_predictions_with_geometry_rerun-5.gpkg", driver="GPKG")

In [13]:
print("Rows in parquet df:", len(df))
print("Rows after merge:", len(final_gdf))
print("Missing geometries:", final_gdf["geometry"].isna().sum())

Rows in parquet df: 2228
Rows after merge: 2228
Missing geometries: 0

In [14]:
final_gdf.columns

Index(['level_0', 'index', 'gml_id', 'volume_m3', 'label_en',
       'osm_building_type', 'osm_landuse_class', 'osm_landuse_name',
       'gfk_class', 'ALKIS_Landuse_info', 'osm_names', 'alkis_address',
       'email', 'amenity', 'building', 'shop', 'tourism', 'information',
       'tags_search', 'additional_information', 'website', 'sentence',
       'interpreted_type', 'mid_labels', 'bosserhof_class', 'mid_label',
       'geometry'],
      dtype='object')