In [14]:
import pandas as pd

df = pd.read_parquet("predictions_checkpoint.parquet")
df.head()

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,alkis_address,...,tourism,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class,error
0,17,163.316463,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,general_building_context: building_label=Build...,error,[],None,TU LLM call failed: 429 Client Error: 429 for ...
1,18,5501.119241,residential buildings,None,residential,None,Gebäude,residence,None,"Danziger Straße 26 Braunschweig, Stadt",...,None,None,None,None,None,general_building_context: building_label=resid...,error,[],None,TU LLM call failed: 429 Client Error: 429 for ...
2,19,1624.116199,residential buildings,None,residential,None,Gebäude,residence;industrial,None,"Fasanenkamp 10 Braunschweig, Stadt",...,None,None,None,None,None,general_building_context: building_label=resid...,error,[],None,TU LLM call failed: 429 Client Error: 429 for ...
3,20,2482.074274,residential buildings,None,residential,None,Gebäude,residence,None,"Margeritenweg 37 Braunschweig, Stadt",...,None,None,None,None,None,general_building_context: building_label=resid...,error,[],None,TU LLM call failed: 429 Client Error: 429 for ...
4,13,89.209230,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,general_building_context: building_label=Build...,office building,[work],normal office,None

In [15]:
df['interpreted_type'].value_counts()

interpreted_type
residential building                                                    140995
Residential building                                                     55835
Commercial building                                                      33541
commercial building                                                      32103
error                                                                    14757
                                                                         ...
Industrial and residential building                                          1
Supermarket (PENNY)                                                          1
Office headquarters                                                          1
Auto service and dealership                                                  1
Mixed-use building: business/commercial, residential, and industrial         1
Name: count, Length: 12018, dtype: int64

In [16]:
df[df['interpreted_type'] == 'error'].to_parquet("error_predictions.parquet")

In [17]:
# Remove rows where interpreted_type == 'error'
df = df[df['interpreted_type'] != 'error']

In [18]:
df.to_parquet("clean_predictions.parquet")

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 398143 entries, 4 to 412899
Data columns (total 24 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   gml_id                  398143 non-null  object
 1   volume_m3               398143 non-null  float64
 2   label_en                398143 non-null  object
 3   osm_building_type       5259 non-null    object
 4   osm_landuse_class       388220 non-null  object
 5   osm_landuse_name        37374 non-null   object
 6   gfk_class               398143 non-null  object
 7   ALKIS_Landuse_info      378652 non-null  object
 8   osm_names               15037 non-null   object
 9   alkis_address           398143 non-null  object
 10  email                   499 non-null     object
 11  amenity                 4720 non-null    object
 12  building                2624 non-null    object
 13  shop                    2633 non-null    object
 14  tourism                 548 non-null     object
 15  information             0 non-null       object
 16  tags_search             5565 non-null    object
 17  additional_information  1416 non-null    object
 18  website                 2197 non-null    object
 19  sentence                398143 non-null  object
 20  interpreted_type        398143 non-null  object
 21  mid_labels              398143 non-null  object
 22  bosserhof_class         186976 non-null  object
 23  error                   0 non-null       object
dtypes: float64(1), object(23)
memory usage: 75.9+ MB

In [20]:
df.head()

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,alkis_address,...,tourism,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class,error
4,13,89.209230,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,general_building_context: building_label=Build...,office building,[work],normal office,None
5,14,119.566130,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,general_building_context: building_label=Build...,office building,[work],normal office,None
6,15,1033.650498,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,general_building_context: building_label=Build...,office building,[work],normal office,None
7,16,46.560366,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,general_building_context: building_label=Build...,office building,[work],normal office,None
8,0,931.423451,Buildings for business or commerce,None,residential,None,Gebäude,commercial,None,"Ackerweg 2 Braunschweig, Stadt",...,None,None,None,None,None,general_building_context: building_label=Build...,office building,[work],normal office,None

In [21]:
import numpy as np

df['mid_label'] = df['mid_labels'].apply(
    lambda x: np.nan if (
        (isinstance(x, list) and len(x) == 0) or
        (isinstance(x, np.ndarray) and x.size == 0)
    ) else x
)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 398143 entries, 4 to 412899
Data columns (total 25 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   gml_id                  398143 non-null  object
 1   volume_m3               398143 non-null  float64
 2   label_en                398143 non-null  object
 3   osm_building_type       5259 non-null    object
 4   osm_landuse_class       388220 non-null  object
 5   osm_landuse_name        37374 non-null   object
 6   gfk_class               398143 non-null  object
 7   ALKIS_Landuse_info      378652 non-null  object
 8   osm_names               15037 non-null   object
 9   alkis_address           398143 non-null  object
 10  email                   499 non-null     object
 11  amenity                 4720 non-null    object
 12  building                2624 non-null    object
 13  shop                    2633 non-null    object
 14  tourism                 548 non-null     object
 15  information             0 non-null       object
 16  tags_search             5565 non-null    object
 17  additional_information  1416 non-null    object
 18  website                 2197 non-null    object
 19  sentence                398143 non-null  object
 20  interpreted_type        398143 non-null  object
 21  mid_labels              398143 non-null  object
 22  bosserhof_class         186976 non-null  object
 23  error                   0 non-null       object
 24  mid_label               167219 non-null  object
dtypes: float64(1), object(24)
memory usage: 79.0+ MB

In [23]:
df = df.reset_index()

In [24]:
import geopandas as gpd

gdf_geom = gpd.read_file("condensed_buildings_with_pois.gpkg")

gdf_geom["gml_id"] = gdf_geom["gml_id"].astype(str)
df["gml_id"] = df["gml_id"].astype(str)

geom_df = gdf_geom[["gml_id", "geometry"]].copy()

merged_df = df.merge(geom_df, on="gml_id", how="left")

final_gdf = gpd.GeoDataFrame(merged_df, geometry="geometry", crs=gdf_geom.crs)

final_gdf.to_file("final_predictions_with_geometry_test.gpkg", driver="GPKG")

In [25]:
print("Rows in parquet df:", len(df))
print("Rows after merge:", len(final_gdf))
print("Missing geometries:", final_gdf["geometry"].isna().sum())

Rows in parquet df: 398143
Rows after merge: 398143
Missing geometries: 0

In [26]:
final_gdf.columns

Index(['index', 'gml_id', 'volume_m3', 'label_en', 'osm_building_type',
       'osm_landuse_class', 'osm_landuse_name', 'gfk_class',
       'ALKIS_Landuse_info', 'osm_names', 'alkis_address', 'email', 'amenity',
       'building', 'shop', 'tourism', 'information', 'tags_search',
       'additional_information', 'website', 'sentence', 'interpreted_type',
       'mid_labels', 'bosserhof_class', 'error', 'mid_label', 'geometry'],
      dtype='object')