In [ ]:
import pandas as pd

df = pd.read_parquet("predictions_checkpoint.parquet")
df.head()

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,alkis_address,...,shop,tourism,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class
0,57917,3084.101807,Church,None,residential,None,Gebäude,public_office,['St. Romanus'],St. Romanus Kirche Hahausen,...,None,None,None,None,['religion: christian'],None,This row describes one building. Building iden...,error,[],None
1,77030,71.731907,Cooling tower,None,industrial,Harzer Zinkoxide GmbH;Industriepark- und Verwe...,Turm,industrial,None,"Bad Harzburg, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,error,[],None
2,30117,454.372915,Buildings for business or commerce,train_station,None,None,Gebäude,None,['Braunschweig Hauptbahnhof'],"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,Braunschweig Hauptbahnhof (train station),[work],Transport
3,38620,1083.248885,residential buildings,train_station,nature_reserve,Landschaftsschutzgebiet „Buchhorst“,Gebäude,commercial,['Empfangsgebäude ehem. Reichsjägerhof'],"Ebertallee 44F Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,Empfangsgebäude ehem. Reichsjägerhof (visitor/...,"[leisure, work]","entertainment, culture"
4,132082,7212.960785,Buildings for business or commerce,train_station,None,None,Gebäude,residence,['Hauptbahnhof'],"Helmstedt, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,error,[],None

In [2]:
df['interpreted_type'].value_counts()

interpreted_type
error                                                                      44
residential building                                                       18
shed                                                                        6
Residential building                                                        6
Cooling tower                                                               3
Commercial building (business or commerce)                                  2
private garage                                                              2
wastewater treatment plant digester building                                2
digester building (wastewater/biogas treatment)                             2
anaerobic digester building                                                 2
garage                                                                      2
Small service utility building (shed)                                       2
Station building                                                            2
Residential building (dwelling)                                             2
Farm supply/storage building (farmyard)                                     1
transportation building                                                     1
parking garage                                                              1
Gasometer (gasholder)                                                       1
Digester building                                                           1
Business/commercial building in forest setting (likely forestry office)     1
Friedhofskapelle (cemetery chapel)                                          1
Farm auxiliary building (e.g. barn or storage outbuilding)                  1
silo                                                                        1
Supply building                                                             1
digester                                                                    1
Empfangsgebäude ehem. Reichsjägerhof (visitor/reception building)           1
commercial building                                                         1
digester building                                                           1
Unknown small building (building=yes)                                       1
Unknown small building                                                      1
Residential building (private home)                                         1
B.O.C. bicycle retail store                                                 1
Agricultural residential building (farmhouse)                               1
utility supply building                                                     1
florist shop in a mixed-use residential building                            1
Dorfkirche (church)                                                         1
St.-Stephanus-Kirche (church)                                               1
chapel                                                                      1
Braunschweig Hauptbahnhof (main train station)                              1
Small retail/commercial building                                            1
St. Altfrid Catholic Church                                                 1
Braunschweig Hauptbahnhof (train station)                                   1
Church (Maria Schnee)                                                       1
Maria Königin Church (Roman Catholic place of worship)                      1
commercial building for commerce                                            1
farm supply building                                                        1
Chapel (Kreuzkapelle)                                                       1
Name: count, dtype: int64

In [3]:
df[df['interpreted_type'] == 'error'].to_parquet("error_predictions.parquet")

In [4]:
# Remove rows where interpreted_type == 'error'
df = df[df['interpreted_type'] != 'error']

In [ ]:
df.to_parquet("clean_predictions.parquet")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 84 entries, 2 to 127
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gml_id                  84 non-null     object
 1   volume_m3               84 non-null     float64
 2   label_en                53 non-null     object
 3   osm_building_type       40 non-null     object
 4   osm_landuse_class       48 non-null     object
 5   osm_landuse_name        11 non-null     object
 6   gfk_class               53 non-null     object
 7   ALKIS_Landuse_info      41 non-null     object
 8   osm_names               14 non-null     object
 9   alkis_address           53 non-null     object
 10  email                   0 non-null      object
 11  amenity                 6 non-null      object
 12  building                7 non-null      object
 13  shop                    2 non-null      object
 14  tourism                 0 non-null      object
 15  information             0 non-null      object
 16  tags_search             7 non-null      object
 17  additional_information  6 non-null      object
 18  website                 0 non-null      object
 19  sentence                84 non-null     object
 20  interpreted_type        84 non-null     object
 21  mid_labels              84 non-null     object
 22  bosserhof_class         34 non-null     object
dtypes: float64(1), object(22)
memory usage: 15.8+ KB

In [7]:
df.head()

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,alkis_address,...,shop,tourism,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class
2,30117,454.372915,Buildings for business or commerce,train_station,None,None,Gebäude,None,['Braunschweig Hauptbahnhof'],"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,Braunschweig Hauptbahnhof (train station),[work],Transport
3,38620,1083.248885,residential buildings,train_station,nature_reserve,Landschaftsschutzgebiet „Buchhorst“,Gebäude,commercial,['Empfangsgebäude ehem. Reichsjägerhof'],"Ebertallee 44F Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,Empfangsgebäude ehem. Reichsjägerhof (visitor/...,"[leisure, work]","entertainment, culture"
6,77031,3599.694412,Cooling tower,None,industrial,Harzer Zinkoxide GmbH;Industriepark- und Verwe...,Turm,industrial,None,"Bad Harzburg, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,Cooling tower,[work],highly productive industries / machine / mater...
7,118070,34.653353,Buildings for supply,None,None,None,Gebäude,None,None,Beierstedt,...,None,None,None,None,None,None,This row describes one building. Building iden...,Supply building,[],None
8,162287,82.418101,Station building,None,None,None,Gebäude,None,None,"Salzgitter, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,Station building,"[errands, work]",Transport

In [8]:
import numpy as np

df['mid_label'] = df['mid_labels'].apply(
    lambda x: np.nan if (
        (isinstance(x, list) and len(x) == 0) or
        (isinstance(x, np.ndarray) and x.size == 0)
    ) else x
)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 84 entries, 2 to 127
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gml_id                  84 non-null     object
 1   volume_m3               84 non-null     float64
 2   label_en                53 non-null     object
 3   osm_building_type       40 non-null     object
 4   osm_landuse_class       48 non-null     object
 5   osm_landuse_name        11 non-null     object
 6   gfk_class               53 non-null     object
 7   ALKIS_Landuse_info      41 non-null     object
 8   osm_names               14 non-null     object
 9   alkis_address           53 non-null     object
 10  email                   0 non-null      object
 11  amenity                 6 non-null      object
 12  building                7 non-null      object
 13  shop                    2 non-null      object
 14  tourism                 0 non-null      object
 15  information             0 non-null      object
 16  tags_search             7 non-null      object
 17  additional_information  6 non-null      object
 18  website                 0 non-null      object
 19  sentence                84 non-null     object
 20  interpreted_type        84 non-null     object
 21  mid_labels              84 non-null     object
 22  bosserhof_class         34 non-null     object
 23  mid_label               34 non-null     object
dtypes: float64(1), object(23)
memory usage: 16.4+ KB

In [10]:
df = df.reset_index()

In [ ]:
import geopandas as gpd

gdf_geom = gpd.read_file("condensed_buildings_with_pois.gpkg")

gdf_geom["gml_id"] = gdf_geom["gml_id"].astype(str)
df["gml_id"] = df["gml_id"].astype(str)

geom_df = gdf_geom[["gml_id", "geometry"]].copy()

merged_df = df.merge(geom_df, on="gml_id", how="left")

final_gdf = gpd.GeoDataFrame(merged_df, geometry="geometry", crs=gdf_geom.crs)

final_gdf.to_file("final_predictions_with_geometry_4.gpkg", driver="GPKG")

In [12]:
print("Rows in parquet df:", len(df))
print("Rows after merge:", len(final_gdf))
print("Missing geometries:", final_gdf["geometry"].isna().sum())

Rows in parquet df: 84
Rows after merge: 84
Missing geometries: 0

In [13]:
final_gdf.columns

Index(['index', 'gml_id', 'volume_m3', 'label_en', 'osm_building_type',
       'osm_landuse_class', 'osm_landuse_name', 'gfk_class',
       'ALKIS_Landuse_info', 'osm_names', 'alkis_address', 'email', 'amenity',
       'building', 'shop', 'tourism', 'information', 'tags_search',
       'additional_information', 'website', 'sentence', 'interpreted_type',
       'mid_labels', 'bosserhof_class', 'mid_label', 'geometry'],
      dtype='object')