In [1]:
import pandas as pd

df = pd.read_parquet("predictions_checkpoint(error-rows).parquet")
df.head()

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,alkis_address,...,shop,tourism,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class
0,35,768.978437,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,commercial office building,[work],normal office
1,132,32.019822,residential buildings,None,allotments,KGV Auf dem Klei,Gebäude,None,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,allotment garden cottage / shed,[],None
2,133,113.601310,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,small commercial office building,[work],normal office
3,134,116.654250,Buildings for business or commerce,None,residential,None,Gebäude,commercial,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,small commercial office building,[work],normal office
4,8,35.568276,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,Residential building,[],None

In [2]:
df['interpreted_type'].value_counts()

interpreted_type
residential building                                            15057
Residential building                                             9324
error                                                            4809
Commercial building                                              1136
commercial building                                               736
                                                                ...
Holiday chalet (tourist bungalow)                                   1
Mixed residential and commercial building (trade & services)        1
guest house (hotel)                                                 1
Water supply plant building                                         1
Schulcontainer (temporary classroom units)                          1
Name: count, Length: 4912, dtype: int64

In [3]:
df[df['interpreted_type'] == 'error'].to_parquet("error_predictions.parquet")

In [4]:
# Remove rows where interpreted_type == 'error'
df = df[df['interpreted_type'] != 'error']

In [5]:
df.to_parquet("clean_predictions_1.parquet")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47648 entries, 0 to 52456
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gml_id                  47648 non-null  object
 1   volume_m3               47648 non-null  float64
 2   label_en                42894 non-null  object
 3   osm_building_type       5214 non-null   object
 4   osm_landuse_class       41696 non-null  object
 5   osm_landuse_name        3917 non-null   object
 6   gfk_class               42894 non-null  object
 7   ALKIS_Landuse_info      40506 non-null  object
 8   osm_names               1491 non-null   object
 9   alkis_address           43594 non-null  object
 10  email                   66 non-null     object
 11  amenity                 673 non-null    object
 12  building                491 non-null    object
 13  shop                    319 non-null    object
 14  tourism                 84 non-null     object
 15  information             0 non-null      object
 16  tags_search             783 non-null    object
 17  additional_information  288 non-null    object
 18  website                 306 non-null    object
 19  sentence                47648 non-null  object
 20  interpreted_type        47648 non-null  object
 21  mid_labels              47648 non-null  object
 22  bosserhof_class         12683 non-null  object
dtypes: float64(1), object(22)
memory usage: 8.7+ MB

In [7]:
df.head()

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,alkis_address,...,shop,tourism,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class
0,35,768.978437,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,commercial office building,[work],normal office
1,132,32.019822,residential buildings,None,allotments,KGV Auf dem Klei,Gebäude,None,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,allotment garden cottage / shed,[],None
2,133,113.601310,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,small commercial office building,[work],normal office
3,134,116.654250,Buildings for business or commerce,None,residential,None,Gebäude,commercial,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,small commercial office building,[work],normal office
4,8,35.568276,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,This row describes one building. Building iden...,Residential building,[],None

In [8]:
import numpy as np

df['mid_label'] = df['mid_labels'].apply(
    lambda x: np.nan if (
        (isinstance(x, list) and len(x) == 0) or
        (isinstance(x, np.ndarray) and x.size == 0)
    ) else x
)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47648 entries, 0 to 52456
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gml_id                  47648 non-null  object
 1   volume_m3               47648 non-null  float64
 2   label_en                42894 non-null  object
 3   osm_building_type       5214 non-null   object
 4   osm_landuse_class       41696 non-null  object
 5   osm_landuse_name        3917 non-null   object
 6   gfk_class               42894 non-null  object
 7   ALKIS_Landuse_info      40506 non-null  object
 8   osm_names               1491 non-null   object
 9   alkis_address           43594 non-null  object
 10  email                   66 non-null     object
 11  amenity                 673 non-null    object
 12  building                491 non-null    object
 13  shop                    319 non-null    object
 14  tourism                 84 non-null     object
 15  information             0 non-null      object
 16  tags_search             783 non-null    object
 17  additional_information  288 non-null    object
 18  website                 306 non-null    object
 19  sentence                47648 non-null  object
 20  interpreted_type        47648 non-null  object
 21  mid_labels              47648 non-null  object
 22  bosserhof_class         12683 non-null  object
 23  mid_label               12964 non-null  object
dtypes: float64(1), object(23)
memory usage: 9.1+ MB

In [10]:
df = df.reset_index()

In [11]:
import geopandas as gpd

gdf_geom = gpd.read_file("condensed_buildings_with_pois.gpkg")

gdf_geom["gml_id"] = gdf_geom["gml_id"].astype(str)
df["gml_id"] = df["gml_id"].astype(str)

geom_df = gdf_geom[["gml_id", "geometry"]].copy()

merged_df = df.merge(geom_df, on="gml_id", how="left")

final_gdf = gpd.GeoDataFrame(merged_df, geometry="geometry", crs=gdf_geom.crs)

final_gdf.to_file("final_predictions_with_geometry_1.gpkg", driver="GPKG")

In [12]:
print("Rows in parquet df:", len(df))
print("Rows after merge:", len(final_gdf))
print("Missing geometries:", final_gdf["geometry"].isna().sum())

Rows in parquet df: 47648
Rows after merge: 47648
Missing geometries: 0

In [13]:
final_gdf.columns

Index(['index', 'gml_id', 'volume_m3', 'label_en', 'osm_building_type',
       'osm_landuse_class', 'osm_landuse_name', 'gfk_class',
       'ALKIS_Landuse_info', 'osm_names', 'alkis_address', 'email', 'amenity',
       'building', 'shop', 'tourism', 'information', 'tags_search',
       'additional_information', 'website', 'sentence', 'interpreted_type',
       'mid_labels', 'bosserhof_class', 'mid_label', 'geometry'],
      dtype='object')