In [15]:
import pandas as pd

df = pd.read_parquet("predictions_checkpoint(error-rows)-1.parquet")
df.head()

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,alkis_address,...,shop,tourism,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class
0,2874,3398.563611,residential buildings,None,residential,None,Gebäude,residence,None,"Krefeldstraße 9 Braunschweig, Stadt",...,None,None,None,None,None,None,general_building_context: building_label=resid...,Residential building,[],None
1,2875,1245.411387,residential buildings,None,residential,None,Gebäude,residence,None,"Wuppertaler Straße 34 Braunschweig, Stadt",...,None,None,None,None,None,None,general_building_context: building_label=resid...,Residential building,[],None
2,2876,183.287954,residential buildings,None,residential,None,Gebäude,commercial,['Öffentlicher Bücherschrank'],"Steinriedendamm 14 Braunschweig, Stadt",...,None,None,None,None,None,None,precise_known_info: name=['Öffentlicher Bücher...,Public bookcase,[],None
3,2877,731.957320,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,general_building_context: building_label=Build...,Commercial office building,[work],normal office
4,17,163.316463,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,general_building_context: building_label=Build...,Commercial building,[work],customer-oriented services

In [16]:
df['interpreted_type'].value_counts()

interpreted_type
residential building                          6039
error                                         3176
Residential building                          1885
commercial building                            841
Commercial building                            748
                                              ...
indoor riding hall                               1
Agrarmeteorological research centre              1
Residence (Bergermühle)                          1
Bergermühle (commercial building)                1
Roof structure (not an enterable building)       1
Name: count, Length: 748, dtype: int64

In [17]:
df[df['interpreted_type'] == 'error'].to_parquet("error_predictions-1.parquet")

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16742 entries, 0 to 16741
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gml_id                  16742 non-null  object
 1   volume_m3               16742 non-null  float64
 2   label_en                15525 non-null  object
 3   osm_building_type       1384 non-null   object
 4   osm_landuse_class       14736 non-null  object
 5   osm_landuse_name        1131 non-null   object
 6   gfk_class               15525 non-null  object
 7   ALKIS_Landuse_info      14644 non-null  object
 8   osm_names               551 non-null    object
 9   alkis_address           15714 non-null  object
 10  email                   18 non-null     object
 11  amenity                 169 non-null    object
 12  building                113 non-null    object
 13  shop                    81 non-null     object
 14  tourism                 26 non-null     object
 15  information             0 non-null      object
 16  tags_search             192 non-null    object
 17  additional_information  52 non-null     object
 18  website                 67 non-null     object
 19  sentence                16742 non-null  object
 20  interpreted_type        16742 non-null  object
 21  mid_labels              16742 non-null  object
 22  bosserhof_class         4364 non-null   object
dtypes: float64(1), object(22)
memory usage: 2.9+ MB

In [19]:
# Remove rows where interpreted_type == 'error'
df = df[df['interpreted_type'] != 'error']

In [20]:
# df.to_parquet("clean_predictions-1.parquet")

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13566 entries, 0 to 16741
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gml_id                  13566 non-null  object
 1   volume_m3               13566 non-null  float64
 2   label_en                12577 non-null  object
 3   osm_building_type       1117 non-null   object
 4   osm_landuse_class       11910 non-null  object
 5   osm_landuse_name        878 non-null    object
 6   gfk_class               12577 non-null  object
 7   ALKIS_Landuse_info      11825 non-null  object
 8   osm_names               445 non-null    object
 9   alkis_address           12727 non-null  object
 10  email                   16 non-null     object
 11  amenity                 138 non-null    object
 12  building                89 non-null     object
 13  shop                    65 non-null     object
 14  tourism                 19 non-null     object
 15  information             0 non-null      object
 16  tags_search             155 non-null    object
 17  additional_information  42 non-null     object
 18  website                 51 non-null     object
 19  sentence                13566 non-null  object
 20  interpreted_type        13566 non-null  object
 21  mid_labels              13566 non-null  object
 22  bosserhof_class         4364 non-null   object
dtypes: float64(1), object(22)
memory usage: 2.5+ MB

In [22]:
df.head()

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,alkis_address,...,shop,tourism,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class
0,2874,3398.563611,residential buildings,None,residential,None,Gebäude,residence,None,"Krefeldstraße 9 Braunschweig, Stadt",...,None,None,None,None,None,None,general_building_context: building_label=resid...,Residential building,[],None
1,2875,1245.411387,residential buildings,None,residential,None,Gebäude,residence,None,"Wuppertaler Straße 34 Braunschweig, Stadt",...,None,None,None,None,None,None,general_building_context: building_label=resid...,Residential building,[],None
2,2876,183.287954,residential buildings,None,residential,None,Gebäude,commercial,['Öffentlicher Bücherschrank'],"Steinriedendamm 14 Braunschweig, Stadt",...,None,None,None,None,None,None,precise_known_info: name=['Öffentlicher Bücher...,Public bookcase,[],None
3,2877,731.957320,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,general_building_context: building_label=Build...,Commercial office building,[work],normal office
4,17,163.316463,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,None,None,general_building_context: building_label=Build...,Commercial building,[work],customer-oriented services

In [23]:
import numpy as np

df['mid_label'] = df['mid_labels'].apply(
    lambda x: np.nan if (
        (isinstance(x, list) and len(x) == 0) or
        (isinstance(x, np.ndarray) and x.size == 0)
    ) else x
)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13566 entries, 0 to 16741
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gml_id                  13566 non-null  object
 1   volume_m3               13566 non-null  float64
 2   label_en                12577 non-null  object
 3   osm_building_type       1117 non-null   object
 4   osm_landuse_class       11910 non-null  object
 5   osm_landuse_name        878 non-null    object
 6   gfk_class               12577 non-null  object
 7   ALKIS_Landuse_info      11825 non-null  object
 8   osm_names               445 non-null    object
 9   alkis_address           12727 non-null  object
 10  email                   16 non-null     object
 11  amenity                 138 non-null    object
 12  building                89 non-null     object
 13  shop                    65 non-null     object
 14  tourism                 19 non-null     object
 15  information             0 non-null      object
 16  tags_search             155 non-null    object
 17  additional_information  42 non-null     object
 18  website                 51 non-null     object
 19  sentence                13566 non-null  object
 20  interpreted_type        13566 non-null  object
 21  mid_labels              13566 non-null  object
 22  bosserhof_class         4364 non-null   object
 23  mid_label               3476 non-null   object
dtypes: float64(1), object(23)
memory usage: 2.6+ MB

In [25]:
df = df.reset_index()

In [26]:
import geopandas as gpd

gdf_geom = gpd.read_file("condensed_buildings_with_pois.gpkg")

gdf_geom["gml_id"] = gdf_geom["gml_id"].astype(str)
df["gml_id"] = df["gml_id"].astype(str)

geom_df = gdf_geom[["gml_id", "geometry"]].copy()

merged_df = df.merge(geom_df, on="gml_id", how="left")

final_gdf = gpd.GeoDataFrame(merged_df, geometry="geometry", crs=gdf_geom.crs)

final_gdf.to_file("final_predictions_with_geometry_rerun-1.gpkg", driver="GPKG")

In [27]:
print("Rows in parquet df:", len(df))
print("Rows after merge:", len(final_gdf))
print("Missing geometries:", final_gdf["geometry"].isna().sum())

Rows in parquet df: 13566
Rows after merge: 13566
Missing geometries: 0

In [28]:
final_gdf.columns

Index(['index', 'gml_id', 'volume_m3', 'label_en', 'osm_building_type',
       'osm_landuse_class', 'osm_landuse_name', 'gfk_class',
       'ALKIS_Landuse_info', 'osm_names', 'alkis_address', 'email', 'amenity',
       'building', 'shop', 'tourism', 'information', 'tags_search',
       'additional_information', 'website', 'sentence', 'interpreted_type',
       'mid_labels', 'bosserhof_class', 'mid_label', 'geometry'],
      dtype='object')