In [1]:
import geopandas as gpd
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.width", 0)

gdf = gpd.read_file('Areas-of-interest-POIs/Enriched-building-volume-data.gpkg')
print(gdf.crs)

EPSG:25832

In [2]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 655874 entries, 0 to 655873
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   gml_id              655874 non-null  object
 1   measHeight          655874 non-null  float64
 2   function            655874 non-null  object
 3   Stadt               655874 non-null  object
 4   Strasse             242814 non-null  object
 5   HausNr              242814 non-null  object
 6   Name                4904 non-null    object
 7   area_m2             655874 non-null  float64
 8   volume_m3           655874 non-null  float64
 9   label_de            655874 non-null  object
 10  label_en            655874 non-null  object
 11  osm_names           15231 non-null   object
 12  osm_building_type   7242 non-null    object
 13  osm_landuse_class   637646 non-null  object
 14  osm_landuse_name    57287 non-null   object
 15  gfk_class           655874 non-null  object
 16  gfk_name            655874 non-null  object
 17  activities          655874 non-null  object
 18  ALKIS_Landuse_info  620897 non-null  object
 19  geometry            655874 non-null  geometry
dtypes: float64(3), geometry(1), object(16)
memory usage: 100.1+ MB

In [3]:
gdf = gdf.drop(['measHeight', 'function', 'area_m2'],axis=1)

In [4]:
gdf.head()

,gml_id,Stadt,Strasse,HausNr,Name,volume_m3,label_de,label_en,osm_names,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,gfk_name,activities,ALKIS_Landuse_info,geometry
0,DENILD01000000Fg,"Braunschweig, Stadt",None,None,None,13.990511,Mast,mast,None,None,farmland,None,Bauwerk oder Anlage für Industrie und Gewerbe,Mast,work,None,MULTIPOLYGON Z (((608736.257 5799617.417 95.25...
1,DENILD01000000Fh,"Braunschweig, Stadt",None,None,None,13.991576,Mast,mast,None,None,farmland,None,Bauwerk oder Anlage für Industrie und Gewerbe,Mast,work,None,MULTIPOLYGON Z (((608534.443 5799829.37 94.225...
2,DENILD01000002A1,"Braunschweig, Stadt",Ackerweg,2,None,931.423451,Gebäude für Wirtschaft oder Gewerbe,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,work;business,commercial,MULTIPOLYGON Z (((609554.181 5797264.172 78.94...
3,DENILD01000002A3,"Braunschweig, Stadt",Stieglitzweg,3,None,1275.527533,Gebäude für Wirtschaft oder Gewerbe,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,work;business,commercial,MULTIPOLYGON Z (((608098.849 5796746.146 83.91...
4,DENILD01000002A4,"Braunschweig, Stadt",None,None,None,229.902499,Gebäude für Wirtschaft oder Gewerbe,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,work;business,residence,"MULTIPOLYGON Z (((608926.355 5797165.768 84.6,..."

In [5]:
gdf["alkis_address"] = (
    gdf[["Name", "Strasse", "HausNr", "Stadt"]]
    .apply(
        lambda row: " ".join(
            [str(v) for v in row if pd.notna(v) and str(v).strip() != ""]
        ),
        axis=1
    )
)

gdf = gdf.drop(["Name", "Strasse", "HausNr", "Stadt"], axis=1)

gdf.head()

,gml_id,volume_m3,label_de,label_en,osm_names,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,gfk_name,activities,ALKIS_Landuse_info,geometry,alkis_address
0,DENILD01000000Fg,13.990511,Mast,mast,None,None,farmland,None,Bauwerk oder Anlage für Industrie und Gewerbe,Mast,work,None,MULTIPOLYGON Z (((608736.257 5799617.417 95.25...,"Braunschweig, Stadt"
1,DENILD01000000Fh,13.991576,Mast,mast,None,None,farmland,None,Bauwerk oder Anlage für Industrie und Gewerbe,Mast,work,None,MULTIPOLYGON Z (((608534.443 5799829.37 94.225...,"Braunschweig, Stadt"
2,DENILD01000002A1,931.423451,Gebäude für Wirtschaft oder Gewerbe,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,work;business,commercial,MULTIPOLYGON Z (((609554.181 5797264.172 78.94...,"Ackerweg 2 Braunschweig, Stadt"
3,DENILD01000002A3,1275.527533,Gebäude für Wirtschaft oder Gewerbe,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,work;business,commercial,MULTIPOLYGON Z (((608098.849 5796746.146 83.91...,"Stieglitzweg 3 Braunschweig, Stadt"
4,DENILD01000002A4,229.902499,Gebäude für Wirtschaft oder Gewerbe,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,work;business,residence,"MULTIPOLYGON Z (((608926.355 5797165.768 84.6,...","Braunschweig, Stadt"

In [6]:
gdf = gdf[['gml_id','volume_m3','label_en','osm_names','osm_building_type','osm_landuse_class','osm_landuse_name','gfk_class','gfk_name','ALKIS_Landuse_info','alkis_address','geometry']]
gdf.head()

,gml_id,volume_m3,label_en,osm_names,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,gfk_name,ALKIS_Landuse_info,alkis_address,geometry
0,DENILD01000000Fg,13.990511,mast,None,None,farmland,None,Bauwerk oder Anlage für Industrie und Gewerbe,Mast,None,"Braunschweig, Stadt",MULTIPOLYGON Z (((608736.257 5799617.417 95.25...
1,DENILD01000000Fh,13.991576,mast,None,None,farmland,None,Bauwerk oder Anlage für Industrie und Gewerbe,Mast,None,"Braunschweig, Stadt",MULTIPOLYGON Z (((608534.443 5799829.37 94.225...
2,DENILD01000002A1,931.423451,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,commercial,"Ackerweg 2 Braunschweig, Stadt",MULTIPOLYGON Z (((609554.181 5797264.172 78.94...
3,DENILD01000002A3,1275.527533,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,commercial,"Stieglitzweg 3 Braunschweig, Stadt",MULTIPOLYGON Z (((608098.849 5796746.146 83.91...
4,DENILD01000002A4,229.902499,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,residence,"Braunschweig, Stadt","MULTIPOLYGON Z (((608926.355 5797165.768 84.6,..."

In [7]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 655874 entries, 0 to 655873
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   gml_id              655874 non-null  object
 1   volume_m3           655874 non-null  float64
 2   label_en            655874 non-null  object
 3   osm_names           15231 non-null   object
 4   osm_building_type   7242 non-null    object
 5   osm_landuse_class   637646 non-null  object
 6   osm_landuse_name    57287 non-null   object
 7   gfk_class           655874 non-null  object
 8   gfk_name            655874 non-null  object
 9   ALKIS_Landuse_info  620897 non-null  object
 10  alkis_address       655874 non-null  object
 11  geometry            655874 non-null  geometry
dtypes: float64(1), geometry(1), object(10)
memory usage: 60.0+ MB

In [8]:
gdf['label_en'].value_counts()

label_en
Buildings for business or commerce             262484
residential buildings                          243201
canopy                                          90647
Agricultural and forestry business building     11912
Commercial and industrial buildings              7913
                                                ...
Control tower                                       4
Station building                                    4
Castle, fortress                                    3
parliament                                          2
Fire lookout tower                                  1
Name: count, Length: 88, dtype: int64

In [9]:
labels_to_remove = ['canopy',
                    'Agricultural and forestry business building',
                    'Buildings for supplying energy', 
                    'silo',
                    'mast',
                    'Solar cells',
                    'Wind turbine',
                    'Operational building for road traffic',
                    'tank',
                    'Radio mast',
                    'chimney',
                    'barracks',
                    'Transmission and radio tower',
                    'Creation',
                    'Observation tower',
                    'Water tower',
                    'Windmill',
                    'ski jump (inrun)']  # useless building types for our use case

gdf = gdf[~gdf["label_en"].apply(
    lambda x: any(label in labels_to_remove for label in (x if isinstance(x, list) else [x]))
)]

In [10]:
osm_building_types = gpd.read_file('Areas-of-interest-POIs/ALL_BUILDINGS.gpkg') # to fill in the missing buildings in ALKIS we use OSM building dataset
# (newly constructed buildings are missing in ALKIS)

In [11]:
osm_building_types.columns

Index(['addr:city', 'addr:country', 'addr:housenumber', 'addr:housename',
       'addr:postcode', 'addr:place', 'addr:street', 'email', 'name',
       'opening_hours', 'operator', 'phone', 'ref', 'url', 'visible',
       'website', 'building', 'amenity', 'building:flats', 'building:levels',
       'building:material', 'building:min_level', 'building:use', 'craft',
       'height', 'internet_access', 'landuse', 'levels', 'office', 'shop',
       'source', 'start_date', 'wikipedia', 'id', 'timestamp', 'version',
       'tags', 'osm_type', 'changeset', 'geometry'],
      dtype='object')

In [12]:
import numpy as np

TARGET_CRS = 25832
DEFAULT_FLOOR_HEIGHT = 2.0
DEFAULT_FLOORS = 1

# keep ONLY the final schema you want
final_cols = [
    'gml_id', 'volume_m3', 'label_en', 'osm_names', 'osm_building_type',
    'osm_landuse_class', 'osm_landuse_name', 'gfk_class', 'gfk_name',
    'ALKIS_Landuse_info', 'alkis_address', 'geometry'
]

gdf_base = gdf[final_cols].copy()
osm_fill = osm_building_types.copy()

# keep only polygonal OSM buildings
osm_fill = osm_fill[osm_fill.geom_type.isin(["Polygon", "MultiPolygon"])].copy()

# keep only actual buildings
osm_fill = osm_fill[osm_fill["building"].notna()].copy()

# project both
gdf_base = gdf_base.to_crs(TARGET_CRS)
osm_fill = osm_fill.to_crs(TARGET_CRS)

# fix invalid geometries
gdf_base["geometry"] = gdf_base.geometry.buffer(0)
osm_fill["geometry"] = osm_fill.geometry.buffer(0)

# drop empty geometries
gdf_base = gdf_base[gdf_base.geometry.notna() & ~gdf_base.geometry.is_empty].copy()
osm_fill = osm_fill[osm_fill.geometry.notna() & ~osm_fill.geometry.is_empty].copy()

# find OSM buildings missing in ALKIS
join_check = gpd.sjoin(
    osm_fill,
    gdf_base[["geometry"]],
    how="left",
    predicate="intersects"
)

osm_missing = join_check[join_check["index_right"].isna()].copy()
osm_missing = osm_fill.loc[osm_missing.index].copy()

def to_float_safe(x):
    if pd.isna(x):
        return np.nan
    try:
        return float(str(x).replace(",", "."))
    except:
        return np.nan

def infer_height_m(row):
    h = to_float_safe(row.get("height"))
    if pd.notna(h):
        return h

    levels = to_float_safe(row.get("building:levels"))
    if pd.notna(levels):
        return levels * DEFAULT_FLOOR_HEIGHT

    return DEFAULT_FLOORS * DEFAULT_FLOOR_HEIGHT

def build_address(row):
    parts = [
        row.get("addr:street"),
        row.get("addr:housenumber"),
        row.get("addr:postcode"),
        row.get("addr:city"),
    ]
    parts = [str(p).strip() for p in parts if pd.notna(p) and str(p).strip() != ""]
    return ", ".join(parts) if parts else None

volume_m3 = osm_missing.geometry.area * osm_missing.apply(infer_height_m, axis=1)

# build ONLY the target schema
osm_to_add = pd.DataFrame(index=osm_missing.index)
osm_to_add["gml_id"] = "osm_" + osm_missing["id"].astype(str)
osm_to_add["volume_m3"] = volume_m3
osm_to_add["label_en"] = pd.NA
osm_to_add["osm_names"] = osm_missing["name"]               # put OSM name here
osm_to_add["osm_building_type"] = osm_missing["building"]
osm_to_add["osm_landuse_class"] = osm_missing["landuse"]
osm_to_add["osm_landuse_name"] = osm_missing["landuse"]
osm_to_add["gfk_class"] = pd.NA
osm_to_add["gfk_name"] = pd.NA
osm_to_add["ALKIS_Landuse_info"] = pd.NA
osm_to_add["alkis_address"] = osm_missing.apply(build_address, axis=1)
osm_to_add["geometry"] = osm_missing.geometry

osm_to_add = gpd.GeoDataFrame(osm_to_add, geometry="geometry", crs=TARGET_CRS)

# force exact same columns before concat
osm_to_add = osm_to_add[final_cols]
gdf_base = gdf_base[final_cols]

gdf = pd.concat([gdf_base, osm_to_add], ignore_index=True)
gdf = gpd.GeoDataFrame(gdf, geometry="geometry", crs=TARGET_CRS)

print("ALKIS buildings:", len(gdf_base))
print("Added OSM-only buildings:", len(osm_to_add))
print("Final total buildings:", len(gdf))

ALKIS buildings: 547150
Added OSM-only buildings: 54024
Final total buildings: 601174

In [13]:
gdf.to_file("Areas-of-interest-POIs/gdf.gpkg") # save the final building dataframe!

In [14]:
osm_pois = gpd.read_file('Areas-of-interest-POIs/OSM-POIs-modified.gpkg')
osm_pois.head()

,id,email,name,website,amenity,building,shop,tourism,information,addr:full,tags_search,additional_information,geometry
0,23654979,None,"Jugendhotel ""Drei Bären""",None,None,None,None,hostel,None,"Auf der Rose, 11, Clausthal-Zellerfeld, 38707",addr suburb altenau schulenberg im oberharz ch...,None,POINT (10.44708 51.79586)
1,23657656,goslar@jugendherberge.de,DJH Jugendherberge Goslar,https://goslar.jugendherberge.de/,None,None,None,hostel,None,"Rammelsberger Straße, 25, Goslar, 38644",beds 163 business conference rooms capacity be...,internet_access: wlan;terminal,POINT (10.41911 51.89897)
2,23657903,hankensbuettel@jugendherberge.de,DJH Jugendherberge Hankensbüttel,https://www.jugendherberge.de/299,None,None,None,hostel,None,"Helmrichsweg, 24, Hankensbüttel, 29386",beds 156 business conference rooms capacity be...,internet_access: wlan; guest_house: hostel,POINT (10.60845 52.72488)
3,29683760,None,None,None,None,None,None,information,guidepost,None,None,None,POINT (10.57783 51.7821)
4,29683806,None,None,None,None,None,None,information,guidepost,None,ele 837 hiking yes,None,POINT (10.57268 51.7765)

In [15]:
osm_pois.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 86542 entries, 0 to 86541
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      86542 non-null  int64
 1   email                   1251 non-null   object
 2   name                    31843 non-null  object
 3   website                 6237 non-null   object
 4   amenity                 66788 non-null  object
 5   building                8110 non-null   object
 6   shop                    8021 non-null   object
 7   tourism                 12051 non-null  object
 8   information             8186 non-null   object
 9   addr:full               13039 non-null  object
 10  tags_search             62266 non-null  object
 11  additional_information  20951 non-null  object
 12  geometry                86542 non-null  geometry
dtypes: geometry(1), int64(1), object(11)
memory usage: 8.6+ MB

In [16]:
osm_pois.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [17]:
osm_pois.geom_type.value_counts()

Point              55261
Polygon            31180
LineString            47
MultiLineString       27
MultiPolygon          27
Name: count, dtype: int64

In [18]:
# Remove lines
clean_pois = osm_pois[
    ~osm_pois.geom_type.isin(["LineString", "MultiLineString"])
].copy()

# Project to metric CRS
clean_pois = clean_pois.to_crs(25832)

# Convert polygons → representative points
polygon_mask = clean_pois.geom_type.isin(["Polygon", "MultiPolygon"])
clean_pois.loc[polygon_mask, "geometry"] = (
    clean_pois.loc[polygon_mask, "geometry"].representative_point()
)

# Convert back (optional)
clean_pois = clean_pois.to_crs(4326)

In [19]:
clean_pois.geom_type.value_counts()

Point    86468
Name: count, dtype: int64

In [20]:
# ensure same CRS
if gdf.crs != clean_pois.crs:
    clean_pois = clean_pois.to_crs(gdf.crs)

print(gdf.crs, clean_pois.crs)

EPSG:25832 EPSG:25832

In [21]:
clean_pois.to_file("Areas-of-interest-POIs/OSM-POIs-modified-cleaned.gpkg")

In [22]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 601174 entries, 0 to 601173
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   gml_id              601174 non-null  object
 1   volume_m3           601174 non-null  float64
 2   label_en            547150 non-null  object
 3   osm_names           12544 non-null   object
 4   osm_building_type   59378 non-null   object
 5   osm_landuse_class   533537 non-null  object
 6   osm_landuse_name    48725 non-null   object
 7   gfk_class           547150 non-null  object
 8   gfk_name            547150 non-null  object
 9   ALKIS_Landuse_info  519592 non-null  object
 10  alkis_address       556501 non-null  object
 11  geometry            601174 non-null  geometry
dtypes: float64(1), geometry(1), object(10)
memory usage: 55.0+ MB

In [23]:
clean_pois = gpd.read_file("Areas-of-interest-POIs/OSM-POIs-modified-cleaned-final.gpkg") # imported from QGIS after clipping to the area of interest
clean_pois.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 68250 entries, 0 to 68249
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      68250 non-null  int64
 1   email                   1047 non-null   object
 2   name                    24981 non-null  object
 3   website                 4963 non-null   object
 4   amenity                 52693 non-null  object
 5   building                6301 non-null   object
 6   shop                    6176 non-null   object
 7   tourism                 9623 non-null   object
 8   information             6641 non-null   object
 9   addr:full               10046 non-null  object
 10  tags_search             50551 non-null  object
 11  additional_information  17598 non-null  object
 12  geometry                68250 non-null  geometry
dtypes: geometry(1), int64(1), object(11)
memory usage: 6.8+ MB

In [24]:
clean_pois['building'].value_counts()

building
yes           3654
church         400
retail         369
house          328
commercial     259
              ...
castle           1
stadium          1
store            1
hall             1
carport          1
Name: count, Length: 70, dtype: int64

In [25]:
exclude_amenities = [
    'parking',
    'bench',
    'parking_space',
    'waste_basket',
    'bicycle_parking',
    'hunting_stand',
    'recycling',
    'shelter',
    'post_box',
    'vending_machine',
    'charging_station',
    'grit_bin',
    'parking_entrance',
    'parcel_locker',
    'fountain',
    'grave_yard',
    'waste_disposal',
    'toilets',
    'drinking_water',
    'bicycle_rental',
    'taxi',
    'clock',
    'car_sharing',
    'trolley_bay',
    'motorcycle_parking',
    'marketplace',
    'atm',
    'lounger',
    'telephone',
    'bicycle_repair_station',
    'kneipp_water_cure',
    'bus_station',
    'loading_dock',
    'compressed_air',
    'letter_box',
    'nest_box',
    'vacuum_cleaner',
    'sanitary_dump_station',
    'water_point',
    'binoculars',
    'animal_training',
    'feeding_place',
    'weighbridge',
    'ticket_validator',
    'stables',
    'smoking_area',
    'information',
    'water',
    'table',
    'traffic_park',
    'boat_rental',
    'b#',
    'scooter_parking',
    'kick-scooter_rental',
    'wildlife_feeding',
    'snow_removal_station',
    'public_bath',
    'small_electric_vehicle_parking',
    'waste_basket;vending_machine',
    'deer_feeding',
    'public_viewing',
    'bicycle_wash',
    'waste_basket;bench',
    'vending_machine;waste_basket',
    'be',
    'passenger_information_display',
    'locker',
    'vending_machine;bicycle_parking',
    'baby_hatch',
    'weight_station',
    'bench;deer_feeding',
    'bbq'
]

exclude_set = set(exclude_amenities)
data_set = set(clean_pois["amenity"].dropna().unique())

missing = exclude_set - data_set

if missing:
    raise ValueError(f"These amenity values were not found in data: {missing}")

clean_pois = clean_pois[
    ~clean_pois["amenity"].isin(exclude_amenities)
].copy()

In [26]:
exclude_buildings = [
    'roof',
    'shed',
    'hut',
    'container',
    'no'
]

exclude_set = set(exclude_buildings)
data_set = set(clean_pois["building"].dropna().unique())

missing = exclude_set - data_set

if missing:
    raise ValueError(f"These building values were not found in data: {missing}")

clean_pois = clean_pois[
    ~clean_pois["building"].isin(exclude_buildings  )
].copy()

In [27]:
allowed_tourism = [
    'chalet',
    'hotel',
    'museum',
    'apartment',
    'guest_house',
    'hostel',
    'theme_park',
    'gallery'
]

clean_pois = clean_pois[
    clean_pois["tourism"].isna() |
    clean_pois["tourism"].isin(allowed_tourism)
].copy()

In [28]:
allowed_information = [
    'office'
]

clean_pois = clean_pois[
    clean_pois["information"].isna() |
    clean_pois["information"].isin(allowed_information)
].copy()

In [29]:
clean_pois.info()
clean_pois.to_file("Areas-of-interest-POIs/OSM-POIs-modified-cleaned-final.gpkg")

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 16194 entries, 0 to 68249
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      16194 non-null  int64
 1   email                   961 non-null    object
 2   name                    14934 non-null  object
 3   website                 4267 non-null   object
 4   amenity                 9017 non-null   object
 5   building                5283 non-null   object
 6   shop                    6156 non-null   object
 7   tourism                 1178 non-null   object
 8   information             0 non-null      object
 9   addr:full               9607 non-null   object
 10  tags_search             12191 non-null  object
 11  additional_information  2511 non-null   object
 12  geometry                16194 non-null  geometry
dtypes: geometry(1), int64(1), object(11)
memory usage: 1.7+ MB

In [30]:
def clean_join_cols(df):
    return df.drop(columns=["index_right", "index_left"], errors="ignore")

gdf = clean_join_cols(gdf.to_crs(25832).copy())
clean_pois = clean_join_cols(clean_pois.to_crs(25832).copy())

gdf["gml_id"] = gdf.index

# direct intersect
pois_joined = gpd.sjoin(
    clean_join_cols(clean_pois),
    gdf[["gml_id", "geometry"]],
    how="left",
    predicate="intersects"
)

pois_joined["match_type"] = pois_joined["gml_id"].notna().map(
    {True: "intersects", False: None}
)

matched = pois_joined[pois_joined["gml_id"].notna()].copy()
unmatched_initial = pois_joined[pois_joined["gml_id"].isna()].copy()

# nearest fallback for non-intersecting POIs
if not unmatched_initial.empty:
    nearest = gpd.sjoin_nearest(
        clean_join_cols(unmatched_initial.drop(columns=["gml_id"], errors="ignore")),
        gdf[["gml_id", "geometry"]],
        how="left",
        max_distance=100,
        distance_col="snap_dist"
    )

    nearest["match_type"] = nearest["gml_id"].notna().map(
        {True: "nearest", False: "unmatched"}
    )

    pois_final = pd.concat([matched, nearest], ignore_index=True)

    # only POIs that still found no building even after nearest
    unmatched_final = nearest[nearest["gml_id"].isna()].copy()

else:
    pois_final = matched.copy()
    unmatched_final = unmatched_initial.copy()

# merge back to buildings
result = gdf.merge(
    pois_final.drop(columns="geometry"),
    on="gml_id",
    how="left"
)

# result.to_file("output.gpkg", driver="GPKG")
# unmatched_final.to_file("unmatched_pois.gpkg", driver="GPKG")

In [31]:
print(pois_final["match_type"].value_counts(dropna=False))

match_type
intersects    14254
nearest        1915
unmatched        28
Name: count, dtype: int64

In [32]:
result.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 605761 entries, 0 to 605760
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   gml_id                  605761 non-null  int64
 1   volume_m3               605761 non-null  float64
 2   label_en                551651 non-null  object
 3   osm_names               14549 non-null   object
 4   osm_building_type       60728 non-null   object
 5   osm_landuse_class       537656 non-null  object
 6   osm_landuse_name        49282 non-null   object
 7   gfk_class               551651 non-null  object
 8   gfk_name                551651 non-null  object
 9   ALKIS_Landuse_info      523994 non-null  object
 10  alkis_address           561062 non-null  object
 11  geometry                605761 non-null  geometry
 12  id                      16169 non-null   float64
 13  email                   961 non-null     object
 14  name                    14912 non-null   object
 15  website                 4262 non-null    object
 16  amenity                 9000 non-null    object
 17  building                5284 non-null    object
 18  shop                    6152 non-null    object
 19  tourism                 1174 non-null    object
 20  information             0 non-null       object
 21  addr:full               9605 non-null    object
 22  tags_search             12179 non-null   object
 23  additional_information  2508 non-null    object
 24  index_right             16169 non-null   float64
 25  match_type              16169 non-null   object
 26  snap_dist               1915 non-null    float64
dtypes: float64(4), geometry(1), int64(1), object(21)
memory usage: 124.8+ MB

In [33]:
result.head()

,gml_id,volume_m3,label_en,osm_names,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,gfk_name,ALKIS_Landuse_info,alkis_address,geometry,id,email,name,website,amenity,building,shop,tourism,information,addr:full,tags_search,additional_information,index_right,match_type,snap_dist
0,0,931.423451,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,commercial,"Ackerweg 2 Braunschweig, Stadt","POLYGON Z ((609554.181 5797264.172 78.94, 6095...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1275.527533,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,commercial,"Stieglitzweg 3 Braunschweig, Stadt","POLYGON Z ((608098.849 5796746.146 83.915, 608...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,229.902499,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,residence,"Braunschweig, Stadt","POLYGON Z ((608926.355 5797165.768 84.6, 60892...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,84.748005,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,residence,"Braunschweig, Stadt","POLYGON Z ((609588.957 5797487.563 77.145, 609...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,351.716079,Buildings for business or commerce,None,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,residence,"Braunschweig, Stadt","POLYGON Z ((608902.529 5796965.286 84.84, 6089...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
result['gml_id'].value_counts()

gml_id
354919    140
534998     69
226798     26
143006     23
229910     23
         ...
200553      1
200554      1
200555      1
200556      1
601173      1
Name: count, Length: 601174, dtype: int64

In [35]:
result = result.drop(columns=['index_right',
                              'match_type',
                              'snap_dist',
                              'id'
                            #   'addr:full',
                            #   'alkis_address']
                            ],errors="ignore")

In [36]:
def is_missing(x):
    if x is None:
        return True
    try:
        return pd.isna(x)
    except Exception:
        return False

def flatten_values(series):
    """
    Flatten mixed values from a series into a simple python list.
    Handles scalars, lists, tuples, sets.
    """
    out = []
    for v in series:
        if is_missing(v):
            continue
        if isinstance(v, (list, tuple, set)):
            for item in v:
                if not is_missing(item):
                    out.append(item)
        else:
            out.append(v)
    return out

def unique_preserve_order(values):
    seen = set()
    out = []
    for v in values:
        key = str(v).strip()
        if key == "":
            continue
        if key not in seen:
            seen.add(key)
            out.append(v)
    return out

def first_non_null(series):
    for v in series:
        if not is_missing(v):
            return v
    return None

def merge_to_unique_list(series):
    vals = flatten_values(series)
    vals = [str(v).strip() for v in vals if not is_missing(v) and str(v).strip() != ""]
    vals = unique_preserve_order(vals)
    return vals if vals else None

def merge_names(osm_names_series, name_series):
    """
    Combine existing osm_names + name into one unique list.
    """
    vals = []

    # existing osm_names may already be string/list
    for v in osm_names_series:
        if is_missing(v):
            continue
        if isinstance(v, (list, tuple, set)):
            vals.extend([str(x).strip() for x in v if not is_missing(x) and str(x).strip() != ""])
        else:
            vals.append(str(v).strip())

    # add name column too
    for v in name_series:
        if is_missing(v):
            continue
        vals.append(str(v).strip())

    vals = [v for v in vals if v != ""]
    vals = unique_preserve_order(vals)
    return vals if vals else None

def merge_address(alkis_series, addrfull_series):
    """
    Keep one address field by combining alkis_address and addr:full.
    If both exist and differ, keep both in a single string separated by ' | '.
    """
    vals = []

    for v in alkis_series:
        if not is_missing(v):
            s = str(v).strip()
            if s:
                vals.append(s)

    for v in addrfull_series:
        if not is_missing(v):
            s = str(v).strip()
            if s:
                vals.append(s)

    vals = unique_preserve_order(vals)

    if not vals:
        return None
    if len(vals) == 1:
        return vals[0]

    return " | ".join(vals)

def keep_single_or_first(series):
    """
    For repeated building-level columns.
    If values are repeated, keeps one.
    If not perfectly repeated, keeps first non-null.
    """
    non_null = [v for v in series if not is_missing(v)]
    if not non_null:
        return None
    return non_null[0]


# ---------- columns ----------
single_value_cols = [
    "volume_m3",
    "label_en",
    "osm_building_type",
    "osm_landuse_class",
    "osm_landuse_name",
    "gfk_class",
    "gfk_name",
    "ALKIS_Landuse_info",
    "geometry"
]

list_cols = [
    "email",
    "amenity",
    "building",
    "shop",
    "tourism",
    "information",
    "tags_search",
    "additional_information",
]

def min_non_null(series):
    vals = [v for v in series if not is_missing(v)]
    return min(vals) if vals else None

grouped = result.groupby("gml_id", dropna=False)

rows = []

for gml_id, grp in grouped:
    row = {"gml_id": gml_id}

    # building-level repeated columns
    for col in single_value_cols:
        if col in grp.columns:
            row[col] = keep_single_or_first(grp[col])

    # merge names into one osm_names field
    row["osm_names"] = merge_names(
        grp["osm_names"] if "osm_names" in grp.columns else pd.Series(dtype=object),
        grp["name"] if "name" in grp.columns else pd.Series(dtype=object)
    )

    # merge address fields into one
    row["alkis_address"] = merge_address(
        grp["alkis_address"] if "alkis_address" in grp.columns else pd.Series(dtype=object),
        grp["addr:full"] if "addr:full" in grp.columns else pd.Series(dtype=object)
    )

    # business-level fields as unique lists
    for col in list_cols:
        if col in grp.columns:
            row[col] = merge_to_unique_list(grp[col])

    # optional: keep unique websites too
    if "website" in grp.columns:
        row["website"] = merge_to_unique_list(grp["website"])

    rows.append(row)

condensed = gpd.GeoDataFrame(rows, geometry="geometry", crs=result.crs)

In [37]:
print("Original rows:", len(result))
print("Condensed rows:", len(condensed))
print("Unique gml_id in original:", result["gml_id"].nunique())
print("Unique gml_id in condensed:", condensed["gml_id"].nunique())

Original rows: 605761
Condensed rows: 601174
Unique gml_id in original: 601174
Unique gml_id in condensed: 601174

In [38]:
condensed.head()

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,gfk_name,ALKIS_Landuse_info,geometry,osm_names,alkis_address,email,amenity,building,shop,tourism,information,tags_search,additional_information,website
0,0,931.423451,Buildings for business or commerce,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,commercial,"POLYGON Z ((609554.181 5797264.172 78.94, 6095...",None,"Ackerweg 2 Braunschweig, Stadt",None,None,None,None,None,None,None,None,None
1,1,1275.527533,Buildings for business or commerce,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,commercial,"POLYGON Z ((608098.849 5796746.146 83.915, 608...",None,"Stieglitzweg 3 Braunschweig, Stadt",None,None,None,None,None,None,None,None,None
2,2,229.902499,Buildings for business or commerce,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,residence,"POLYGON Z ((608926.355 5797165.768 84.6, 60892...",None,"Braunschweig, Stadt",None,None,None,None,None,None,None,None,None
3,3,84.748005,Buildings for business or commerce,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,residence,"POLYGON Z ((609588.957 5797487.563 77.145, 609...",None,"Braunschweig, Stadt",None,None,None,None,None,None,None,None,None
4,4,351.716079,Buildings for business or commerce,None,residential,None,Gebäude,Gebäude für Wirtschaft oder Gewerbe,residence,"POLYGON Z ((608902.529 5796965.286 84.84, 6089...",None,"Braunschweig, Stadt",None,None,None,None,None,None,None,None,None

In [39]:
condensed = condensed.drop(columns=["gfk_name"], errors="ignore")

In [40]:
condensed.to_file("Areas-of-interest-POIs/condensed_buildings_with_pois.gpkg")