In [17]:
import geopandas as gpd

df = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun.gpkg"
)

df1 = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun-0.gpkg"
)

df2 = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun-1.gpkg"
)

df3 = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun-2.gpkg"
)

df4 = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun-3.gpkg"
)

df5 = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun-4.gpkg"
)

df6 = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun-5.gpkg"
)

df7 = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun-6.gpkg"
)

df8 = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun-7.gpkg"
)

df9 = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun-8.gpkg"
)

df10 = gpd.read_file(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\final_predictions_with_geometry_rerun-9.gpkg"
)

print(len(df))
print(len(df1))
print(len(df2))
print(len(df3))
print(len(df4))
print(len(df5))
print(len(df6))
print(len(df7))
print(len(df8))
print(len(df9))
print(len(df10))

561338
27042
13566
2476
700
9891
2228
3400
1032
712
68

In [18]:
import pandas as pd
import geopandas as gpd

# Put all dataframes in order
dfs = {
    "df": df,
    "df1": df1,
    "df2": df2,
    "df3": df3,
    "df4": df4,
    "df5": df5,
    "df6": df6,
    "df7": df7,
    "df8": df8,
    "df9": df9,
    "df10": df10,
}

# Make sure gml_id is string everywhere
for name, d in dfs.items():
    d["gml_id"] = d["gml_id"].astype(str)

# Start with df as base
merged_gdf = df.copy()

stats = []

for name, new_df in list(dfs.items())[1:]:
    before_count = len(merged_gdf)

    existing_ids = set(merged_gdf["gml_id"])
    new_ids = set(new_df["gml_id"])

    replaced_ids = existing_ids & new_ids
    added_ids = new_ids - existing_ids

    replaced_count = len(replaced_ids)
    added_count = len(added_ids)

    # Remove old rows that will be replaced
    merged_gdf = merged_gdf[~merged_gdf["gml_id"].isin(replaced_ids)]

    # Add all rows from the new dataframe
    # This includes both replacement rows and new rows
    merged_gdf = pd.concat([merged_gdf, new_df], ignore_index=True)

    after_count = len(merged_gdf)

    stats.append({
        "dataset": name,
        "input_rows": len(new_df),
        "added": added_count,
        "replaced": replaced_count,
        "rows_before": before_count,
        "rows_after": after_count,
    })

stats_df = pd.DataFrame(stats)

print(stats_df)

print("\nBrief summary:")
print(f"Initial rows in df: {len(df)}")
print(f"Final merged rows: {len(merged_gdf)}")
print(f"Total added rows: {stats_df['added'].sum()}")
print(f"Total replaced rows: {stats_df['replaced'].sum()}")
print(f"Duplicate gml_id count after merge: {merged_gdf['gml_id'].duplicated().sum()}")

# Convert back to GeoDataFrame
merged_gdf = gpd.GeoDataFrame(
    merged_gdf,
    geometry="geometry",
    crs=df.crs
)

  dataset  input_rows  added  replaced  rows_before  rows_after
0     df1       27042      0     27042       561338      561338
1     df2       13566  13566         0       561338      574904
2     df3        2476   2476         0       574904      577380
3     df4         700    700         0       577380      578080
4     df5        9891      0      9891       578080      578080
5     df6        2228      0      2228       578080      578080
6     df7        3400      0      3400       578080      578080
7     df8        1032      0      1032       578080      578080
8     df9         712      0       712       578080      578080
9    df10          68      0        68       578080      578080

Brief summary:
Initial rows in df: 561338
Final merged rows: 578080
Total added rows: 16742
Total replaced rows: 44373
Duplicate gml_id count after merge: 0

In [19]:
merged_gdf.columns

Index(['index', 'gml_id', 'volume_m3', 'label_en', 'osm_building_type',
       'osm_landuse_class', 'osm_landuse_name', 'gfk_class',
       'ALKIS_Landuse_info', 'osm_names', 'alkis_address', 'email', 'amenity',
       'building', 'shop', 'tourism', 'information', 'tags_search',
       'additional_information', 'website', 'sentence', 'interpreted_type',
       'mid_labels', 'bosserhof_class', 'error', 'mid_label', 'geometry',
       'gml_id_pred', 'short_reason', 'level_0'],
      dtype='object')

In [20]:
merged_gdf.head()

,index,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,...,sentence,interpreted_type,mid_labels,bosserhof_class,error,mid_label,geometry,gml_id_pred,short_reason,level_0
0,4.0,13,89.209230,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,general_building_context: building_label=Build...,office building,['work'],normal office,None,['work'],MULTIPOLYGON Z (((608781.076 5797034.372 86.80...,NaN,NaN,NaN
1,5.0,14,119.566130,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,general_building_context: building_label=Build...,office building,['work'],normal office,None,['work'],"MULTIPOLYGON Z (((609122.06 5797462.983 85.46,...",NaN,NaN,NaN
2,6.0,15,1033.650498,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,general_building_context: building_label=Build...,office building,['work'],normal office,None,['work'],MULTIPOLYGON Z (((609428.62 5797079.031 79.962...,NaN,NaN,NaN
3,7.0,16,46.560366,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,...,general_building_context: building_label=Build...,office building,['work'],normal office,None,['work'],"MULTIPOLYGON Z (((609661.688 5797071.969 77.4,...",NaN,NaN,NaN
4,8.0,0,931.423451,Buildings for business or commerce,None,residential,None,Gebäude,commercial,None,...,general_building_context: building_label=Build...,office building,['work'],normal office,None,['work'],MULTIPOLYGON Z (((609554.181 5797264.172 78.94...,NaN,NaN,NaN

In [21]:
merged_gdf.isna().sum()

index                       8205
gml_id                         0
volume_m3                      0
label_en                   44503
osm_building_type         526410
osm_landuse_class          58091
osm_landuse_name          530802
gfk_class                  44503
ALKIS_Landuse_info         68807
osm_names                 555281
alkis_address              35418
email                     577171
amenity                   570100
building                  572935
shop                      573285
tourism                   576936
information               578080
tags_search               568172
additional_information    575670
website                   574211
sentence                       0
interpreted_type               0
mid_labels                     0
bosserhof_class           313940
error                     578080
mid_label                 314567
geometry                       0
gml_id_pred               575582
short_reason              575582
level_0                   565928
dtype: int64

In [22]:
merged_gdf = merged_gdf.drop(columns=['index','error', 'gml_id_pred', 'short_reason', 'level_0'],axis=1)

In [23]:
merged_gdf.head()

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,alkis_address,...,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class,mid_label,geometry
0,13,89.209230,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,general_building_context: building_label=Build...,office building,['work'],normal office,['work'],MULTIPOLYGON Z (((608781.076 5797034.372 86.80...
1,14,119.566130,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,general_building_context: building_label=Build...,office building,['work'],normal office,['work'],"MULTIPOLYGON Z (((609122.06 5797462.983 85.46,..."
2,15,1033.650498,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,general_building_context: building_label=Build...,office building,['work'],normal office,['work'],MULTIPOLYGON Z (((609428.62 5797079.031 79.962...
3,16,46.560366,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,"Braunschweig, Stadt",...,None,None,None,None,general_building_context: building_label=Build...,office building,['work'],normal office,['work'],"MULTIPOLYGON Z (((609661.688 5797071.969 77.4,..."
4,0,931.423451,Buildings for business or commerce,None,residential,None,Gebäude,commercial,None,"Ackerweg 2 Braunschweig, Stadt",...,None,None,None,None,general_building_context: building_label=Build...,office building,['work'],normal office,['work'],MULTIPOLYGON Z (((609554.181 5797264.172 78.94...

In [24]:
filtered_df = merged_gdf[
    merged_gdf["mid_label"].isna()
    & merged_gdf["bosserhof_class"].notna()
].copy()

print(len(filtered_df))
filtered_df.head()

627

,gml_id,volume_m3,label_en,osm_building_type,osm_landuse_class,osm_landuse_name,gfk_class,ALKIS_Landuse_info,osm_names,alkis_address,...,information,tags_search,additional_information,website,sentence,interpreted_type,mid_labels,bosserhof_class,mid_label,geometry
563457,397624,670.054586,"Sports hall, gymnasium",None,forest,None,Gebäude,None,None,"Schützenhaus Goslar, Stadt",...,None,None,None,None,This row describes one building. Building iden...,Sports hall (gymnasium),['sports'],fitness / wellness,NaN,MULTIPOLYGON Z (((607072.491 5760494.212 127.5...
563459,400166,1461.716628,Buildings for trade and services,None,retail,None,Gebäude,commercial,None,"Goslar, Stadt",...,None,None,None,None,This row describes one building. Building iden...,Commercial retail building for trade and services,"['work', 'retail_non_daily']",retail (small-scale),NaN,MULTIPOLYGON Z (((599677.078 5752635.174 237.0...
563462,403988,157.880679,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,Hohenhameln,...,None,None,None,None,This row describes one building. Building iden...,Commercial office building,['work'],normal office,NaN,MULTIPOLYGON Z (((572531.719 5790101.795 95.78...
563464,499019,84.953851,Buildings for business or commerce,None,residential,None,Gebäude,residence,None,Tülau,...,None,None,None,None,This row describes one building. Building iden...,Building for business or commerce,['work'],normal office,NaN,MULTIPOLYGON Z (((627334.726 5827378.095 75.01...
563465,97698,116.329761,Buildings for supply,None,residential,None,Gebäude,residence;public_office,None,Lehre,...,None,None,None,None,This row describes one building. Building iden...,Public office building,"['errands', 'work']",customer-oriented services,NaN,MULTIPOLYGON Z (((611392.123 5797629.341 79.53...

In [25]:
import ast
import pandas as pd

ALLOWED_LABELS = [
    "retail_non_daily",
    "retail_daily",
    "university",
    "childcare",
    "business",
    "errands",
    "lessons",
    "leisure",
    "school",
    "sports",
    "meetup",
    "work",
]

# Important: longest first, so retail_non_daily is found before retail_daily
ALLOWED_LABELS_SORTED = sorted(ALLOWED_LABELS, key=len, reverse=True)


def split_glued_labels(text):
    text = str(text).strip()

    found = []
    remaining = text

    for label in ALLOWED_LABELS_SORTED:
        if label in remaining:
            found.append(label)
            remaining = remaining.replace(label, "")

    return found if found else pd.NA


def clean_mid_labels(value):
    if value is None or pd.isna(value):
        return pd.NA

    if isinstance(value, list):
        raw_items = value
    elif isinstance(value, str):
        value = value.strip()

        if value in ["", "[]", "nan", "None"]:
            return pd.NA

        try:
            parsed = ast.literal_eval(value)
            raw_items = parsed if isinstance(parsed, list) else [value]
        except Exception:
            raw_items = [value]
    else:
        return pd.NA

    cleaned = []

    for item in raw_items:
        item = str(item).strip()

        if item in ALLOWED_LABELS:
            cleaned.append(item)
        else:
            split_items = split_glued_labels(item)
            if split_items is not pd.NA:
                cleaned.extend(split_items)

    # remove duplicates but keep order
    cleaned = list(dict.fromkeys(cleaned))

    return cleaned if cleaned else pd.NA


merged_gdf["mid_label"] = merged_gdf["mid_labels"].apply(clean_mid_labels)

print("NaN count:", merged_gdf["mid_label"].isna().sum())

merged_gdf[["mid_labels", "mid_label"]].head()

NaN count: 313940

  mid_labels mid_label
0   ['work']    [work]
1   ['work']    [work]
2   ['work']    [work]
3   ['work']    [work]
4   ['work']    [work]

In [26]:
filtered_df = merged_gdf[
    merged_gdf["mid_label"].isna()
    & merged_gdf["bosserhof_class"].notna()
].copy()

print(len(filtered_df))

0

In [27]:
filtered_df.to_parquet(
    r"Areas-of-interest-POIs\Data-created(2nd LLM run)\filtered_mid_label_empty.parquet",
    index=False
)

In [28]:
final_df = merged_gdf[['gml_id', 'osm_names', 'volume_m3', 'sentence', 'interpreted_type', 'bosserhof_class', 'mid_label', 'geometry']]
final_df.head()

,gml_id,osm_names,volume_m3,sentence,interpreted_type,bosserhof_class,mid_label,geometry
0,13,None,89.209230,general_building_context: building_label=Build...,office building,normal office,[work],MULTIPOLYGON Z (((608781.076 5797034.372 86.80...
1,14,None,119.566130,general_building_context: building_label=Build...,office building,normal office,[work],"MULTIPOLYGON Z (((609122.06 5797462.983 85.46,..."
2,15,None,1033.650498,general_building_context: building_label=Build...,office building,normal office,[work],MULTIPOLYGON Z (((609428.62 5797079.031 79.962...
3,16,None,46.560366,general_building_context: building_label=Build...,office building,normal office,[work],"MULTIPOLYGON Z (((609661.688 5797071.969 77.4,..."
4,0,None,931.423451,general_building_context: building_label=Build...,office building,normal office,[work],MULTIPOLYGON Z (((609554.181 5797264.172 78.94...

In [29]:
final_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 578080 entries, 0 to 578079
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   gml_id            578080 non-null  object
 1   osm_names         22799 non-null   object
 2   volume_m3         578080 non-null  float64
 3   sentence          578080 non-null  object
 4   interpreted_type  578080 non-null  object
 5   bosserhof_class   264140 non-null  object
 6   mid_label         264140 non-null  object
 7   geometry          578080 non-null  geometry
dtypes: float64(1), geometry(1), object(6)
memory usage: 35.3+ MB

In [30]:
final_df.isna().sum()

gml_id                   0
osm_names           555281
volume_m3                0
sentence                 0
interpreted_type         0
bosserhof_class     313940
mid_label           313940
geometry                 0
dtype: int64

In [31]:
filtered_df = final_df[
    final_df["mid_label"].notna() &
    final_df["bosserhof_class"].isna()
]

print("Rows found:", len(filtered_df))

filtered_df

Rows found: 0

Empty GeoDataFrame
Columns: [gml_id, osm_names, volume_m3, sentence, interpreted_type, bosserhof_class, mid_label, geometry]
Index: []