In [13]:
import geopandas as gpd

gdf = gpd.read_file(r"Areas-of-interest-POIs\bs_area_correct.gpkg", layer="regionbsstructuredata_zone")
gdf.head()

,NO,CODE,NAME,TYPENO,RO_LANDK~1,SG_0_EW_~2,SG_1_EW_~3,SG_1_STU~4,SG_2_EWT~5,SG_2_EWT~6,...,SG_6_BE~20,SG_6_BE~21,SG_6_FR~22,SG_6_FR~23,SG_6_FR~24,SG_6_GE~25,SG_6_PR~26,SG_6_SONST,SG_7_AN~27,geometry
0,310101901,None,BS Stadtkern 6,1,Braunschweig,3040,623.50,40.66,106.42,270.12,...,9.0,0.0,176.0,1166.0,990.0,8.0,17.0,0.0,0.0,"MULTIPOLYGON (((603845.77 5791532.411, 603828...."
1,310101902,None,BS Stadtkern 9,1,Braunschweig,2352,175.74,25.38,31.27,79.38,...,11.0,0.0,22.0,772.0,750.0,8.0,7.0,1.0,0.0,"MULTIPOLYGON (((603798.46 5791316.225, 603740...."
2,310101903,None,BS Stadtkern 13,1,Braunschweig,3698,1321.42,109.87,226.38,574.60,...,2.0,0.0,105.0,611.0,506.0,9.0,12.0,0.0,0.0,"MULTIPOLYGON (((603829.121 5790964.967, 603769..."
3,310101904,None,BS Stadtkern 17,1,Braunschweig,2635,148.38,14.42,27.99,71.06,...,1.0,0.0,5.0,745.0,740.0,3.0,1.0,0.0,0.0,"MULTIPOLYGON (((603455.156 5791018.867, 603492..."
4,310101905,None,BS Stadtkern 15,1,Braunschweig,2031,370.40,37.21,67.53,171.40,...,8.0,0.0,17.0,587.0,570.0,9.0,6.0,1.0,0.0,"MULTIPOLYGON (((603968.386 5791312.927, 603981..."

In [14]:
import fiona

layers = fiona.listlayers(r"C:\Users\Mayur Patel\bs_area_correct.gpkg")
print(layers)

['v10_2025_zone', 'regionbsstructuredata_zone']

In [15]:
print(gdf.columns)

Index(['NO', 'CODE', 'NAME', 'TYPENO', 'RO_LANDK~1', 'SG_0_EW_~2',
       'SG_1_EW_~3', 'SG_1_STU~4', 'SG_2_EWT~5', 'SG_2_EWT~6', 'SG_2_EWT~7',
       'SG_3_BES~8', 'SG_3_BES~9', 'SG_3_BE~10', 'SG_3_BE~11', 'SG_3_BE~12',
       'SG_3_BE~13', 'SG_3_BE~14', 'SG_3_BE~15', 'SG_3_BE~16', 'SG_3_BE~17',
       'SG_4_BS', 'SG_4_GSCH', 'SG_4_HS', 'SG_4_KITA', 'SG_4_WFSCH',
       'SG_5_EK~18', 'SG_5_EK~19', 'SG_5_EK_TB', 'SG_6_BE~20', 'SG_6_BE~21',
       'SG_6_FR~22', 'SG_6_FR~23', 'SG_6_FR~24', 'SG_6_GE~25', 'SG_6_PR~26',
       'SG_6_SONST', 'SG_7_AN~27', 'geometry'],
      dtype='object')

In [16]:
gdf.columns[20:29]

Index(['SG_3_BE~17', 'SG_4_BS', 'SG_4_GSCH', 'SG_4_HS', 'SG_4_KITA',
       'SG_4_WFSCH', 'SG_5_EK~18', 'SG_5_EK~19', 'SG_5_EK_TB'],
      dtype='object')

In [17]:
gdf.columns[32]

'SG_6_FR~23'

In [18]:
gdf['Education_School'] = gdf['SG_4_BS'] + gdf['SG_4_GSCH'] + gdf['SG_4_WFSCH']

gdf = gdf.rename(columns={
    'SG_3_BE~17': 'Workers',
    'SG_4_HS': 'University_Students',
    'SG_4_KITA': 'Kindergarten',
    'SG_5_EK~18': 'Shopping_Total',
    'SG_5_EK~19': 'Shopping_NonEssential',
    'SG_5_EK_TB': 'Shopping_DailyNeeds',
    'SG_6_FR~23': 'Leisure'
})

columns_to_keep = [
    'NAME',
    'Workers',
    'Education_School',
    'University_Students',
    'Kindergarten',
    'Shopping_Total',
    'Shopping_NonEssential',
    'Shopping_DailyNeeds',
    'Leisure',
    'geometry'
]

gdf = gdf[columns_to_keep]

gdf.head()

,NAME,Workers,Education_School,University_Students,Kindergarten,Shopping_Total,Shopping_NonEssential,Shopping_DailyNeeds,Leisure,geometry
0,BS Stadtkern 6,2416.29,0.0,0.0,0,9970.0,8757,1213,1166.0,"MULTIPOLYGON (((603845.77 5791532.411, 603828...."
1,BS Stadtkern 9,2176.16,934.0,0.0,0,26243.0,22039,4204,772.0,"MULTIPOLYGON (((603798.46 5791316.225, 603740...."
2,BS Stadtkern 13,2376.94,428.0,0.0,68,11627.0,11263,364,611.0,"MULTIPOLYGON (((603829.121 5790964.967, 603769..."
3,BS Stadtkern 17,2486.83,0.0,0.0,0,896.0,172,724,745.0,"MULTIPOLYGON (((603455.156 5791018.867, 603492..."
4,BS Stadtkern 15,1660.61,0.0,0.0,0,21637.0,10208,11429,587.0,"MULTIPOLYGON (((603968.386 5791312.927, 603981..."

In [19]:
print(gdf.columns)

Index(['NAME', 'Workers', 'Education_School', 'University_Students',
       'Kindergarten', 'Shopping_Total', 'Shopping_NonEssential',
       'Shopping_DailyNeeds', 'Leisure', 'geometry'],
      dtype='object')

In [20]:
df = gpd.read_file(r"Areas-of-interest-POIs\final_potentials_calculation.gpkg")
df.head()

,gml_id,volume_m3,osm_names,bosserhof_class,mid_label,potentials,geometry
0,0,931.423451,None,normal office,['work'],2701.13,MULTIPOLYGON Z (((609554.181 5797264.172 78.94...
1,1,1275.527533,None,normal office,['work'],3699.03,MULTIPOLYGON Z (((608098.849 5796746.146 83.91...
2,2,229.902499,None,normal office,['work'],666.72,"MULTIPOLYGON Z (((608926.355 5797165.768 84.6,..."
3,3,84.748005,None,normal office,['work'],245.77,MULTIPOLYGON Z (((609588.957 5797487.563 77.14...
4,16,46.560366,None,normal office,['work'],135.03,"MULTIPOLYGON Z (((609661.688 5797071.969 77.4,..."

In [21]:
df['mid_label'].value_counts()

mid_label
['work']                                                          93760
['work' 'business']                                               14966
['work' 'errands']                                                 6972
['leisure']                                                        4771
['work' 'retail_non_daily']                                        4179
                                                                  ...
['work' 'sports' 'lessons' 'leisure' 'meetup']                        1
['work' 'retail_daily' 'retail_non_daily' 'leisure' 'lessons']        1
['retail_daily' 'lessons' 'errands']                                  1
['business' 'lessons' 'leisure']                                      1
['work' 'retail_non_daily' 'lessons']                                 1
Name: count, Length: 407, dtype: int64

In [22]:
import re
import pandas as pd
import numpy as np

valid_labels = [
    "Workers",
    "University",
    "School",
    "Kindergarten",
    "Retail_Daily",
    "Retail_Non-Daily",
    "Leisure",
]

label_map = {
    "work": "Workers",
    "business": "Workers",
    "university": "University",
    "school": "School",
    "childcare": "Kindergarten",
    "retail_daily": "Retail_Daily",
    "retail_non_daily": "Retail_Non-Daily",
    "errands": "Retail_Daily",
    "leisure": "Leisure",
    "sports": "Leisure",
    "meetup": "Leisure",
    "lessons": "Leisure",
}

pattern = re.compile("|".join(sorted(map(re.escape, label_map.keys()), key=len, reverse=True)))


def clean_mid_label(x):
    if x is None:
        return []

    if isinstance(x, float) and pd.isna(x):
        return []

    if isinstance(x, (list, tuple, set, np.ndarray)):
        raw_labels = [str(v).strip() for v in x]
    else:
        raw_labels = pattern.findall(str(x))

    mapped = [label_map[label] for label in raw_labels if label in label_map]

    # remove duplicates, keep order
    return list(dict.fromkeys(mapped))


df["mid_label"] = df["mid_label"].apply(clean_mid_label)

In [24]:
df.head()

,gml_id,volume_m3,osm_names,bosserhof_class,mid_label,potentials,geometry
0,0,931.423451,None,normal office,[Workers],2701.13,MULTIPOLYGON Z (((609554.181 5797264.172 78.94...
1,1,1275.527533,None,normal office,[Workers],3699.03,MULTIPOLYGON Z (((608098.849 5796746.146 83.91...
2,2,229.902499,None,normal office,[Workers],666.72,"MULTIPOLYGON Z (((608926.355 5797165.768 84.6,..."
3,3,84.748005,None,normal office,[Workers],245.77,MULTIPOLYGON Z (((609588.957 5797487.563 77.14...
4,16,46.560366,None,normal office,[Workers],135.03,"MULTIPOLYGON Z (((609661.688 5797071.969 77.4,..."

In [25]:
df['mid_label'].value_counts()

mid_label
[Workers]                                         108824
[Workers, Retail_Daily]                             7760
[Leisure]                                           7549
[Retail_Daily, Workers]                             4722
[Workers, Retail_Non-Daily]                         4211
                                                   ...
[Workers, Leisure, Retail_Daily, Kindergarten]         1
[Leisure, Workers, Retail_Daily]                       1
[University, Workers, Retail_Daily]                    1
[Leisure, Retail_Non-Daily, Retail_Daily]              1
[Retail_Daily, Leisure, Retail_Non-Daily]              1
Name: count, Length: 97, dtype: int64

In [26]:
df.to_file(r"Areas-of-interest-POIs\final_potentials_calculation_test.gpkg", driver="GPKG")

In [23]:
# label_map = {
#     "work": "Workers",
#     "university": "University",
#     "school": "School",
#     "childcare": "Kindergarten",
#     "retail_daily": "Retail_Daily",
#     "retail_non_daily": "Retail_Non-Daily",
#     "leisure": "Leisure",
#     "sports": "Leisure",
#     "errands": "Retail_Daily",
#     "meetup": "Leisure",
#     "lessons": "Leisure",
#     "business": "Workers",

#     # already mapped labels
#     "Workers": "Workers",
#     "University": "University",
#     "School": "School",
#     "Kindergarten": "Kindergarten",
#     "Retail_Daily": "Retail_Daily",
#     "Retail_Non-Daily": "Retail_Non-Daily",
#     "Leisure": "Leisure",
# }